const bookChapters = [
  { part: 'I', partTitle: 'Wprowadzenie', number: 1, title: 'Dziesięć podstawowych zasad ekonomii', sections: ['Co to jest ekonomia?', 'W jaki sposób ludzie podejmują decyzje?', 'W jaki sposób ludzie współdziałają ze sobą?', 'W jaki sposób działa gospodarka?', 'Podsumowanie'] },
  { part: 'I', partTitle: 'Wprowadzenie', number: 2, title: 'Myśleć jak ekonomista', sections: ['Wprowadzenie', 'Ekonomista jako naukowiec', 'Ekonomista jako doradca polityczny', 'Dlaczego ekonomiści różnią się poglądami?', 'Ekonomiści jako decydenci', 'Co dalej?', 'Dodatek: wykresy i inne narzędzia pomocnicze stosowane w ekonomii'] },
  { part: 'II', partTitle: 'Podaż i popyt, czyli jak działają rynki', number: 3, title: 'Podaż i popyt jako siły rynkowe', sections: ['Rynki i konkurencja', 'Popyt', 'Podaż', 'Podaż w połączeniu z popytem', 'Podsumowanie: ceny a alokacja zasobów'] },
  { part: 'II', partTitle: 'Podaż i popyt, czyli jak działają rynki', number: 4, title: 'Elastyczność i jej zastosowania', sections: ['Elastyczność cenowa popytu', 'Inne rodzaje elastyczności popytu', 'Elastyczność cenowa podaży', 'Elastyczność podaży i popytu w praktyce'] },
  { part: 'II', partTitle: 'Podaż i popyt, czyli jak działają rynki', number: 5, title: 'Popyt a teoria wyboru konsumenta', sections: ['Standardowy model ekonomiczny', 'Ograniczenie budżetowe: na co stać konsumenta?', 'Preferencje, czyli czego chce konsument', 'Optymalizacja, czyli co wybiera konsument', 'Ścieżka ekspansji dochodowej', 'Behawioralne spojrzenie na zachowania konsumentów'] },
  { part: 'II', partTitle: 'Podaż i popyt, czyli jak działają rynki', number: 6, title: 'Podaż a przedsiębiorstwa na rynkach konkurencyjnych', sections: ['Koszty produkcji', 'Produkcja i koszty', 'Miary kosztów', 'Koszty w krótkim i długim okresie', 'Przychody ze skali produkcji', 'Co to jest rynek konkurencyjny?', 'Maksymalizacja zysku i krzywa podaży przedsiębiorstwa konkurencyjnego', 'Krzywa podaży na rynku konkurencyjnym', 'Podsumowanie: krzywa podaży'] },
  { part: 'III', partTitle: 'Rynki, efektywność i dobrobyt', number: 7, title: 'Konsumenci, producenci i efektywność rynków', sections: ['Nadwyżka konsumenta', 'Nadwyżka producenta', 'Efektywność rynku', 'Podsumowanie: efektywność rynku i zawodność rynku'] },
  { part: 'III', partTitle: 'Rynki, efektywność i dobrobyt', number: 8, title: 'Podaż, popyt i polityka państwa', sections: ['Regulacja cen', 'Podatki', 'Subwencje', 'Podsumowanie'] },
  { part: 'IV', partTitle: 'Ekonomia sektora publicznego', number: 9, title: 'System podatkowy i koszty opodatkowania', sections: ['Podatki a efektywność', 'Zbędna strata społeczna z tytułu opodatkowania', 'Obciążenia administracyjne', 'Konstrukcja systemu podatkowego', 'Podatki i sprawiedliwość', 'Podsumowanie'] },
  { part: 'V', partTitle: 'Zawodność rynku', number: 10, title: 'Dobra publiczne, zasoby wspólne i dobra społecznie pożądane', sections: ['Rodzaje dóbr', 'Dobra publiczne', 'Zasoby wspólne', 'Dobra społecznie pożądane', 'Podsumowanie'] },
  { part: 'V', partTitle: 'Zawodność rynku', number: 11, title: 'Efekty zewnętrzne i zawodność rynku', sections: ['Koszty i korzyści społeczne wynikające z decyzji podmiotów ekonomicznych', 'Efekty zewnętrzne i nieefektywność rynku', 'Prywatne rozwiązania problemu efektów zewnętrznych', 'Polityka państwa w obszarze efektów zewnętrznych', 'Publiczno-prywatne rozwiązania problemu efektów zewnętrznych', 'Zawodność państwa', 'Podsumowanie'] },
  { part: 'V', partTitle: 'Zawodność rynku', number: 12, title: 'Ekonomia informacji i ekonomia behawioralna', sections: ['„Pan” i „sługa”', 'Asymetria informacji', 'Odchylenia od standardowego modelu ekonomicznego', 'Podsumowanie'] },
  { part: 'VI', partTitle: 'Zachowanie przedsiębiorstw i struktury rynkowe', number: 13, title: 'Decyzje produkcyjne przedsiębiorstw', sections: ['Izokwanty i izokoszty', 'Kombinacja nakładów o najniższym koszcie', 'Zakończenie', 'Podsumowanie'] },
  { part: 'VI', partTitle: 'Zachowanie przedsiębiorstw i struktury rynkowe', number: 14, title: 'Struktury rynkowe: monopol', sections: ['Konkurencja niedoskonała', 'Przyczyny powstawania monopoli', 'Decyzje produkcyjne i cenowe przedsiębiorstw monopolistycznych', 'Koszt społeczny monopolu', 'Różnicowanie cen', 'Polityka państwa wobec monopoli', 'Podsumowanie'] },
  { part: 'VI', partTitle: 'Zachowanie przedsiębiorstw i struktury rynkowe', number: 15, title: 'Konkurencja monopolistyczna', sections: ['Konkurencja między zróżnicowanymi produktami', 'Reklama i budowanie marki', 'Rynki kontestowalne', 'Podsumowanie'] },
  { part: 'VI', partTitle: 'Zachowanie przedsiębiorstw i struktury rynkowe', number: 16, title: 'Oligopol', sections: ['Charakterystyka oligopolu', 'Teoria gier i ekonomia kooperacji', 'Modele oligopolu', 'Polityka państwa wobec oligopoli', 'Podsumowanie'] },
  { part: 'VII', partTitle: 'Rynki czynników produkcji', number: 17, title: 'Ekonomia rynku pracy', sections: ['Popyt na pracę', 'Podaż pracy', 'Równowaga na rynku pracy', 'Zróżnicowanie płac', 'Ekonomia dyskryminacji', 'Pozostałe czynniki produkcji: ziemia i kapitał', 'Renta ekonomiczna', 'Podsumowanie'] },
  { part: 'VIII', partTitle: 'Nierówność', number: 18, title: 'Nierówność dochodowa i ubóstwo', sections: ['Metody pomiaru nierówności dochodowych', 'Filozofia polityczna redystrybucji dochodu', 'Podsumowanie'] },
  { part: 'IX', partTitle: 'Wymiana handlowa', number: 19, title: 'Współzależność i korzyści z wymiany handlowej', sections: ['Granica możliwości produkcyjnych', 'Handel międzynarodowy', 'Zasada korzyści komparatywnych', 'Uwarunkowania wymiany handlowej', 'Kto zyskuje, a kto traci na wymianie handlowej?', 'Bariery handlowe', 'Argumenty za ograniczeniem wolnego handlu', 'Podsumowanie'] }
];

const bookConcepts = [
  { term: 'Agent', definition: 'Osoba, która realizuje jakieś zadanie na rzecz innej osoby, zwanej pryncypałem.', page: 735 },
  { term: 'Aktywność gospodarcza', definition: 'Liczba transakcji kupna/sprzedaży realizowanych w danej gospodarce w pewnym przedziale czasu.', page: 735 },
  { term: 'Analiza kosztów i korzyści', definition: 'Zestawienie ogólnospołecznych kosztów i korzyści związanych z dostarczaniem dobra publicznego.', page: 735 },
  { term: 'Arbitraż', definition: 'Operacja zakupu dobra na jednym rynku po niskiej cenie i sprzedania go na innym rynku po wyższej cenie w celu osiągnięcia zysku na różnicy cen.', page: 735 },
  { term: 'Asymetria informacji', definition: 'Sytuacja, w której strony pewnej relacji różnią się posiadanymi informacjami.', page: 735 },
  { term: 'Bariery wejścia', definition: 'Wszelkie czynniki utrudniające rozpoczęcie działalności na pewnym rynku lub w pewnej branży.', page: 735 },
  { term: 'Barter', definition: 'Wymiana towaru lub usługi na inny towar lub usługę.', page: 735 },
  { term: 'Branding', definition: 'Budowanie marki, czyli wszelkie sposoby kreowania tożsamości przedsiębiorstwa/produktu i podkreślania jego odrębności od konkurentów.', page: 735 },
  { term: 'Cena maksymalna', definition: 'Najwyższa cena, po jakiej zgodnie z prawem można sprzedać dane dobro.', page: 735 },
  { term: 'Cena minimalna', definition: 'Najniższa cena, po jakiej zgodnie z prawem można sprzedać dane dobro.', page: 735 },
  { term: 'Cena równowagi (cena rynkowa)', definition: 'Cena, przy której wielkość zapotrzebowania jest równa ilości oferowanej.', page: 735 },
  { term: 'Cena światowa', definition: 'Cena dobra dominująca na rynku światowym.', page: 735 },
  { term: 'Cena zaporowa', definition: 'Cena ustalona na poziomie niższym niż możliwy do osiągnięcia na danym rynku w celu zniechęcenia potencjalnych wchodzących.', page: 735 },
  { term: 'Ceteris paribus', note: 'łac., „inne takie samo”', definition: 'Termin oznaczający analizę „przy innych czynnikach stałych”, czyli taką, w której tylko jedna zmienna w modelu podlega modyfikacjom.', page: 735 },
  { term: 'Cło', definition: 'Podatek od dobra wytwarzanego za granicą i sprzedawanego na rynku krajowym.', page: 736 },
  { term: 'Cykl życia', definition: 'Typowy schemat zmiany poziomu dochodów w ciągu życia człowieka.', page: 736 },
  { term: 'Długi okres', definition: 'Okres, w którym wszystkie czynniki produkcji mogą ulec zmianie.', page: 736 },
  { term: 'Dobra doskonale komplementarne', definition: 'Dwa dobra, w przypadku których krzywe obojętności są załamane pod kątem prostym.', page: 736 },
  { term: 'Dobra doskonale substytucyjne', definition: 'Dwa dobra, w przypadku których krzywe obojętności są liniami prostymi.', page: 736 },
  { term: 'Dobra klubowe', definition: 'Dobra, które mogą podlegać zastrzeżeniu dostępu, ale ich konsumpcja jest wolna od rywalizacji.', page: 736 },
  { term: 'Dobra komplementarne', definition: 'Dwa dobra, w wypadku których wzrost (spadek) ceny jednego z nich prowadzi do spadku (wzrostu) popytu na drugie.', page: 736 },
  { term: 'Dobra prywatne', definition: 'Dobra, które stanowią przedmiot rywalizacji i mogą podlegać zastrzeżeniu dostępu.', page: 736 },
  { term: 'Dobra publiczne', definition: 'Dobra, które nie stanowią przedmiotu rywalizacji i nie podlegają zastrzeżeniu dostępu.', page: 736 },
  { term: 'Dobra społecznie niepożądane', definition: 'Dobra, które w warunkach wolnego rynku są konsumowane w zbyt dużej ilości oraz niosą ze sobą koszty indywidualne i społeczne pomijane przez konsumentów przy podejmowaniu decyzji zakupowych.', page: 736 },
  { term: 'Dobra społecznie pożądane', definition: 'Dobra, które mogą być dostarczane przez rynek, ale ich konsumpcja jest czasami zbyt niska, ponieważ ludzie nie w pełni zdają sobie sprawę z ich użyteczności.', page: 736 },
  { term: 'Dobra substytucyjne', definition: 'Dwa dobra, w wypadku których wzrost (spadek) ceny jednego z nich prowadzi do wzrostu (spadku) popytu na drugie.', page: 736 },
  { term: 'Dobro Giffena', definition: 'Dobro, w wypadku którego wzrost ceny powoduje wzrost wielkości zapotrzebowania.', page: 736 },
  { term: 'Dobro niższego rzędu', definition: 'Dobro, w wypadku którego wzrost dochodu, przy innych czynnikach stałych, prowadzi do spadku popytu (i odwrotnie).', page: 736 },
  { term: 'Dobro normalne', definition: 'Dobro, w wypadku którego wzrost dochodu, przy innych czynnikach stałych, prowadzi do wzrostu popytu (i odwrotnie).', page: 736 },
  { term: 'Dobro rywalizacyjne', definition: 'Dobro, którego konsumpcję jedna osoba może zwiększyć tylko w wyniku ograniczenia jego konsumpcji przez innych.', page: 736 },
  { term: 'Dobro zastrzegalne', definition: 'Dobro, do którego dostęp można zastrzec dla osób gotowych za nie zapłacić.', page: 736 },
  { term: 'Dobrobyt obiektywny', definition: 'Jakość życia mierzona przy użyciu rozmaitych wskaźników.', page: 736 },
  { term: 'Dobrobyt subiektywny', definition: 'Stopień, w jakim dana osoba czuje się szczęśliwa lub zadowolona z życia.', page: 737 },
  { term: 'Dochód permanentny', definition: 'Przeciętny dochód osiągany przez daną osobę w dłuższym okresie.', page: 737 },
  { term: 'Dochód transferowy', definition: 'Minimalna zapłata niezbędna do utrzymania czynnika produkcji w obecnym obszarze zastosowania.', page: 737 },
  { term: 'Doskonałe różnicowanie ceny', definition: 'Sytuacja, w której monopolista wie dokładnie, ile wynosi skłonność do płacenia każdego klienta, i ma możliwość sprzedania dobra każdemu klientowi po innej cenie.', page: 737 },
  { term: 'Dylemat więźnia', definition: 'Forma „gry” z udziałem dwóch więźniów, która pozwala zrozumieć, dlaczego kooperacja nastręcza trudności, nawet jeśli jest korzystna dla wszystkich stron.', page: 737 },
  { term: 'Dyskryminacja', definition: 'Zachowanie polegające na niejednakowym traktowaniu ludzi wyłącznie z powodu ich przynależności rasowej lub etnicznej, płci, wieku lub innych cech osobowych.', page: 737 },
  { term: 'Efekt dochodowy', definition: 'Zmiana wielkości konsumpcji, do jakiej dochodzi, gdy w wyniku zmiany ceny konsument przesuwa się na inną krzywą obojętności.', page: 737 },
  { term: 'Efekt kontekstu', definition: 'Zjawisko polegające na podejmowaniu odmiennych decyzji w zależności od sposobu przedstawienia możliwości wyboru.', page: 737 },
  { term: 'Efekt posiadania', definition: 'Zjawisko polegające na tym, że pewna rzecz ma dla właściciela większą wartość niż taka sama rzecz należąca do kogoś innego.', page: 737 },
  { term: 'Efekt racjonalnej ignorancji', definition: 'Niechęć wyborcy do poszukiwania informacji ułatwiających rozważne oddanie głosu podczas wyborów.', page: 737 },
  { term: 'Efekt substytucyjny', definition: 'Zmiana wielkości konsumpcji, do jakiej dochodzi, gdy w wyniku zmiany ceny konsument przesuwa się wzdłuż danej krzywej obojętności do punktu o innej krańcowej stopie substytucji.', page: 737 },
  { term: 'Efekt wąskich interesów', definition: 'Zjawisko polegające na tym, że korzyści osiągnięte przez niewielką grupę są mniejsze od kosztów ponoszonych przez większość społeczeństwa.', page: 737 },
  { term: 'Efekt zewnętrzny', definition: 'Pozytywny lub negatywny wpływ decyzji jednej osoby na sytuację innej osoby, który nie został uwzględniony przy podejmowaniu tej decyzji.', page: 737 },
  { term: 'Efektywność', definition: 'Cecha alokacji zasobów oznaczająca maksymalizację nadwyżki całkowitej osiąganej przez wszystkich członków społeczeństwa.', page: 737 },
  { term: 'Efektywność alokacyjna', definition: 'Stan, w którym wartość dóbr wytworzonych przez sprzedawców odpowiada wartości przypisywanej tym dobrom przez nabywców.', page: 737 },
  { term: 'Ekonomia', definition: 'Nauka o tym, w jaki sposób społeczeństwo gospodaruje zasobami rzadkimi.', page: 737 },
  { term: 'Ekonomia dobrobytu', definition: 'Nauka o wpływie alokacji zasobów na dobrobyt ekonomiczny.', page: 738 },
  { term: 'Ekonomia heterodoksyjna', definition: 'Termin oznaczający grupę różnych szkół myślenia, które nie mieszczą się w granicach obszaru uchodzącego za ekonomię głównego nurtu lub ekonomię ortodoksyjną.', page: 738 },
  { term: 'Ekonomia zakresu', definition: 'Sytuacja, w której średni koszt produkcji ulega obniżeniu w wyniku wytwarzania różnych produktów z wykorzystaniem tych samych zasobów.', page: 738 },
  { term: 'Eksport', definition: 'Wywóz dóbr wytworzonych w danym kraju w celu ich sprzedaży za granicą, prowadzący do napływu pieniądza do gospodarki.', page: 738 },
  { term: 'Elastyczność', definition: 'Miara wrażliwości wielkości zapotrzebowania (lub ilości oferowanej) na zmianę jednego z warunkujących ją czynników.', page: 738 },
  { term: 'Elastyczność cenowa podaży', definition: 'Miara siły reakcji ilości oferowanej dobra na zmianę ceny tego dobra. Oblicza się ją jako stosunek procentowej zmiany ilości oferowanej do procentowej zmiany ceny.', page: 738 },
  { term: 'Elastyczność cenowa popytu', definition: 'Miara siły reakcji wielkości zapotrzebowania na dobro na zmianę ceny tego dobra. Oblicza się ją jako stosunek procentowej zmiany wielkości zapotrzebowania do procentowej zmiany ceny.', page: 738 },
  { term: 'Elastyczność dochodowa popytu', definition: 'Miara siły reakcji wielkości zapotrzebowania na dobro na zmianę dochodu nabywców. Oblicza się ją jako stosunek procentowej zmiany wielkości zapotrzebowania do procentowej zmiany dochodu.', page: 738 },
  { term: 'Falsyfikowalność', definition: 'Możliwość odrzucenia teorii w wyniku pojawienia się nowych obserwacji lub nowych danych.', page: 738 },
  { term: 'Funkcja dobrobytu społecznego', definition: 'Użyteczność zbiorowa dla społeczeństwa, obejmująca nadwyżkę konsumenta i nadwyżkę producenta.', page: 738 },
  { term: 'Funkcja produkcji', definition: 'Zależność między wysokością nakładów na produkcję dobra a wielkością produkcji tego dobra.', page: 738 },
  { term: 'Gospodarka', definition: 'Ogół czynności związanych z wytwarzaniem i wymianą dóbr i usług.', page: 738 },
  { term: 'Gospodarka planowa', definition: 'System ekonomiczny, w którym działalność gospodarcza jest organizowana przez centralnych planistów odpowiedzialnych za ustalenie odpowiedzi na podstawowe pytania ekonomiczne.', page: 738 },
  { term: 'Gospodarka rynkowa', definition: 'Gospodarka, która rozstrzyga trzy zasadnicze kwestie składające się na problem ekonomiczny w drodze zdecentralizowanych decyzji wielu przedsiębiorstw i gospodarstw domowych współdziałających ze sobą na rynkach dóbr i usług.', page: 738 },
  { term: 'Gra pozycyjna', definition: 'Gra, w której gracze podejmują decyzje naprzemiennie, z uwzględnieniem decyzji podjętych wcześniej przez innych.', page: 738 },
  { term: 'Granica możliwości produkcyjnych', definition: 'Krzywa wyznaczająca kombinacje dóbr, jakie jest w stanie wytworzyć dana gospodarka na bazie dostępnych zasobów z wykorzystaniem istniejącej technologii.', page: 739 },
  { term: 'Heurystyki', definition: 'Uproszczone reguły wnioskowania stosowane przez ludzi przy podejmowaniu decyzji.', page: 739 },
  { term: 'Hipoteza', definition: 'Założenie, wstępna prognoza, objaśnienie lub przypuszczenie.', page: 739 },
  { term: 'Hipoteza Prebischa-Singera', definition: 'Hipoteza zakładająca, że stosunek wymiany dóbr pierwotnych na dobra przetworzone zmniejsza się z upływem czasu, więc kraje specjalizujące się w produkcji dóbr pierwotnych stają się biedniejsze.', page: 739 },
  { term: 'Ilość oferowana', definition: 'Ilość dobra, jaką sprzedawcy chcą i są w stanie sprzedać przy danej cenie.', page: 739 },
  { term: 'Ilość równowagi', definition: 'Ilość oferowana i wielkość zapotrzebowania przy cenie równowagi.', page: 739 },
  { term: 'Import', definition: 'Przywóz dóbr wytworzonych za granicą w celu ich sprzedaży w danym kraju, prowadzący do odpływu pieniądza z gospodarki.', page: 739 },
  { term: 'Inflacja', definition: 'Wzrost ogólnego poziomu cen w gospodarce.', page: 739 },
  { term: 'Instytucje', definition: 'Reguły rządzące stosunkami międzyludzkimi w danej gospodarce, obejmujące przepisy, normy społeczne i inne stworzone przez człowieka ramy postępowania, które rządzą zachowaniem uczestników rynku.', page: 739 },
  { term: 'Interes publiczny', definition: 'Zasada podejmowania decyzji z myślą o zapewnieniu jak największych korzyści jak największej liczbie ludzi przy jak najmniejszych kosztach.', page: 739 },
  { term: 'Internalizacja efektu zewnętrznego', definition: 'Zmiana bodźców ekonomicznych skłaniająca ludzi do uwzględnienia skutków ubocznych swoich działań przy podejmowaniu decyzji.', page: 739 },
  { term: 'Izokoszta', definition: 'Krzywa wyznaczająca różne kombinacje czynników produkcji, które można nabyć za daną kwotę.', page: 739 },
  { term: 'Izokwanta produkcji', definition: 'Funkcja określająca wszystkie kombinacje czynników produkcji, które można zastosować do wytworzenia danej ilości dobra.', page: 739 },
  { term: 'Kapitał', definition: 'Wszelkie środki materialne wykorzystywane do wytwarzania dóbr i usług.', page: 739 },
  { term: 'Kapitał ludzki', definition: 'Skumulowany efekt inwestycji w rozwój osobisty człowieka, takich jak edukacja czy szkolenia w miejscu pracy.', page: 739 },
  { term: 'Kartel', definition: 'Grupa przedsiębiorstw działających w zmowie.', page: 739 },
  { term: 'Koalicja koniunkturalna', definition: 'Doraźne porozumienie między politykami w sprawie wzajemnego wsparcia w określonych kwestiach.', page: 739 },
  { term: 'Kompromis', definition: 'Rezygnacja z korzyści związanych z odrzuconym rozwiązaniem w zamian za korzyści związane z wybranym rozwiązaniem.', page: 739 },
  { term: 'Konkurencja monopolistyczna', definition: 'Rynek, na którym wiele przedsiębiorstw oferuje podobne, ale nie identyczne produkty.', page: 740 },
  { term: 'Konkurencja niedoskonała', definition: 'Sytuacja, w której przedsiębiorstwa są w stanie odróżnić swoje produkty od innych, w związku z czym mają pewien wpływ na ich ceny.', page: 740 },
  { term: 'Kontyngent przywozowy', definition: 'Maksymalna ilość dobra wytwarzanego za granicą, którą można sprowadzić do danego kraju.', page: 740 },
  { term: 'Korzyści (ekonomia) skali', definition: 'Wzrost efektywności wynikający stąd, że długookresowy przeciętny koszt całkowity maleje wraz ze wzrostem wielkości produkcji.', page: 740 },
  { term: 'Koszt', definition: 'Wartość wszystkiego, z czego sprzedawca musi zrezygnować, by wytworzyć pewne dobro.', page: 740 },
  { term: 'Koszt alternatywny', definition: 'Wszystko, z czego trzeba zrezygnować, żeby w zamian uzyskać coś innego; wartość utraconych (poświęconych) korzyści.', page: 740 },
  { term: 'Koszt krańcowy', definition: 'Przyrost kosztu całkowitego wynikający ze zwiększenia produkcji o jednostkę.', page: 740 },
  { term: 'Koszt krańcowy redukcji zanieczyszczeń', definition: 'Koszt przypadający na ostatnią wyeliminowaną jednostkę zanieczyszczeń.', page: 740 },
  { term: 'Koszty jawne', definition: 'Koszty nakładów związane z wydatkowaniem pieniędzy przez przedsiębiorstwo.', page: 740 },
  { term: 'Koszty stałe', definition: 'Koszty, które nie zmieniają się wraz z wielkością produkcji.', page: 740 },
  { term: 'Koszty transakcyjne', definition: 'Ponoszone przez strony koszty uzgadniania i realizacji porozumienia.', page: 740 },
  { term: 'Koszty ukryte', definition: 'Koszty nakładów niezwiązane z wydatkowaniem pieniędzy przez przedsiębiorstwo.', page: 740 },
  { term: 'Koszty utopione', definition: 'Koszty, które zostały poniesione i nie mogą zostać odzyskane.', page: 740 },
  { term: 'Koszty zmienne', definition: 'Koszty, które zmieniają się wraz z wielkością produkcji.', page: 740 },
  { term: 'Krańcowa stopa podatkowa', definition: 'Wysokość podatku od dodatkowej jednostki dochodu.', page: 740 },
  { term: 'Krańcowa stopa substytucji', definition: 'Stosunek, według którego konsument jest skłonny zamienić jedno dobro na inne.', page: 740 },
  { term: 'Krańcowa stopa substytucji technicznej', definition: 'Współczynnik informujący, w jakim stosunku można wymienić dany czynnik produkcji na inny bez zmiany poziomu produkcji.', page: 740 },
  { term: 'Krańcowy przychód z zasobu', definition: 'Wzrost utargu wynikający ze zwiększenia nakładu czynnika produkcji o jednostkę.', page: 740 },
  { term: 'Krótki okres', definition: 'Okres, w którym pewne czynniki produkcji nie podlegają zmianie.', page: 740 },
  { term: 'Krzywa cena-konsumpcja', definition: 'Krzywa pokazująca, jak zmienia się punkt optymalny konsumenta mającego do wyboru dwa dobra w zależności od ceny jednego z tych dóbr przy założeniu, że dochód konsumenta i cena drugiego dobra są stałe.', page: 740 },
  { term: 'Krzywa Engla', definition: 'Krzywa odzwierciedlająca zależność między popytem a wysokością dochodu.', page: 741 },
  { term: 'Krzywa Lorenza', definition: 'Krzywa pokazująca relację między skumulowanym odsetkiem gospodarstw domowych a skumulowanym odsetkiem dochodu całkowitego.', page: 741 },
  { term: 'Krzywa obojętności', definition: 'Krzywa, która wyznacza koszyki dóbr zapewniające konsumentowi jednakowe zadowolenie.', page: 741 },
  { term: 'Krzywa podaży', definition: 'Wykres pokazujący zależność ilości oferowanej danego dobra od jego ceny.', page: 741 },
  { term: 'Krzywa popytu', definition: 'Wykres pokazujący zależność wielkości zapotrzebowania na dane dobro od jego ceny.', page: 741 },
  { term: 'Kumoterstwo', definition: 'Zjawisko polegające na tym, że o alokacji zasobów na rynku decydują częściowo układy polityczne i znajomości, a nie czynniki ekonomiczne.', page: 741 },
  { term: 'Liberalizm', definition: 'Nurt filozofii politycznej postulujący prowadzenie przez państwo takiej polityki, którą bezstronny obserwator pozostający za „zasłoną niewiedzy” uznałby za sprawiedliwą.', page: 741 },
  { term: 'Libertarianizm', definition: 'Nurt filozofii politycznej, zgodnie z którym państwo powinno się zajmować wyłącznie ściganiem przestępców i egzekwowaniem dobrowolnie zawieranych umów, a nie redystrybucją dochodów.', page: 741 },
  { term: 'Macierz wypłat', definition: 'Tabela przedstawiająca wyniki gry dla każdej możliwej kombinacji strategii wybieranych przez graczy.', page: 741 },
  { term: 'Makroekonomia', definition: 'Nauka o zjawiskach charakteryzujących całą gospodarkę, takich jak inflacja, bezrobocie i wzrost gospodarczy.', page: 741 },
  { term: 'Malejąca użyteczność krańcowa', definition: 'Zjawisko polegające na tym, że dodatkowe zadowolenie płynące z konsumowania kolejnych jednostek dobra jest coraz mniejsze.', page: 741 },
  { term: 'Malejąca wydajność krańcowa', definition: 'Zjawisko polegające na tym, że produkt krańcowy czynnika produkcji maleje wraz ze wzrostem nakładu tego czynnika.', page: 741 },
  { term: 'Mieszana elastyczność cenowa popytu', definition: 'Miara siły reakcji wielkości zapotrzebowania na jedno dobro na zmianę ceny innego dobra. Oblicza się ją jako stosunek procentowej zmiany wielkości zapotrzebowania na pierwsze dobro do procentowej zmiany ceny drugiego dobra.', page: 741 },
  { term: 'Mikroekonomia', definition: 'Nauka o tym, jak gospodarstwa domowe i przedsiębiorstwa podejmują decyzje i współdziałają ze sobą na rynku.', page: 741 },
  { term: 'Mnożenie marek', definition: 'Strategia mająca na celu zniechęcenie nowych konkurentów do wejścia na rynek, polegająca na oferowaniu wielu marek w tej samej kategorii produktów.', page: 741 },
  { term: 'Mobilność ekonomiczna', definition: 'Przepływ ludzi między grupami dochodowymi.', page: 741 },
  { term: 'Monopol', definition: 'Sytuacja, w której na rynku istnieje tylko jeden dostawca produktu pozbawionego bliskich substytutów.', page: 741 },
  { term: 'Monopol naturalny', definition: 'Monopol, który powstaje wtedy, kiedy pojedyncze przedsiębiorstwo jest w stanie zaspokoić całe zapotrzebowanie na dane dobro lub usługę po niższym koszcie niż większa liczba przedsiębiorstw.', page: 742 },
  { term: 'Monopolista', definition: 'Przedsiębiorstwo, które jest jedynym sprzedawcą produktu pozbawionego bliskich substytutów.', page: 742 },
  { term: 'Monopson', definition: 'Sytuacja, w której na rynku istnieje tylko jeden lub dominujący nabywca.', page: 742 },
  { term: 'Nadwyżka', definition: 'Sytuacja, w której ilość oferowana jest większa niż wielkość zapotrzebowania przy bieżącej cenie rynkowej.', page: 742 },
  { term: 'Nadwyżka całkowita', definition: 'Całkowita wartość dóbr dla nabywców mierzona ich skłonnością do płacenia za nie, pomniejszona o koszty dostarczenia tych dóbr ponoszone przez sprzedawców.', page: 742 },
  { term: 'Nadwyżka konsumenta', definition: 'Różnica między kwotą, jaką nabywca jest skłonny zapłacić za dane dobro, a kwotą przez niego zapłaconą.', page: 742 },
  { term: 'Nadwyżka producenta', definition: 'Różnica między kwotą, jaką otrzymuje sprzedawca za dane dobro, a kosztami, jakie poniósł na jego wytworzenie.', page: 742 },
  { term: 'Negatywna selekcja', definition: 'Sytuacja, w której pryncypał zna swoją sytuację lepiej niż agent, więc agent wolałby nie zawierać z nim transakcji.', page: 742 },
  { term: 'Negatywny efekt zewnętrzny', definition: 'Koszt poniesiony przez osobę postronną wskutek czyjejś decyzji.', page: 742 },
  { term: 'Niedobór', definition: 'Sytuacja, w której wielkość zapotrzebowania jest większa niż ilość oferowana przy bieżącej cenie rynkowej.', page: 742 },
  { term: 'Nieefektywność typu X', definition: 'Niezdolność przedsiębiorstwa do działania z maksymalną efektywnością ze względu na brak presji konkurencyjnej i osłabioną motywację do ścisłego kontrolowania kosztów.', page: 742 },
  { term: 'Niekorzyści (dysekonomia) skali', definition: 'Spadek efektywności wynikający stąd, że długookresowy przeciętny koszt całkowity zwiększa się wraz ze wzrostem wielkości produkcji.', page: 742 },
  { term: 'Odsiew', definition: 'Działania podejmowane przez stronę gorzej poinformowaną, by skłonić drugą stronę do ujawnienia posiadanych informacji.', page: 742 },
  { term: 'Ograniczenie budżetowe', definition: 'Zbiór koszyków (kombinacji ilościowych) dóbr, na które stać konsumenta.', page: 742 },
  { term: 'Ograniczona racjonalność', definition: 'Koncepcja, zgodnie z którą ludzie podejmują decyzje na podstawie niepełnych i czasami niepewnych informacji.', page: 742 },
  { term: 'Oligopol', definition: 'Sytuacja, w której rynek jest zdominowany przez kilku sprzedawców identycznych lub podobnych produktów.', page: 742 },
  { term: 'Patent', definition: 'Prawo do wyłącznego korzystania z pewnego rozwiązania technicznego przez jego właściciela.', page: 742 },
  { term: 'Plan podaży', definition: 'Zestawienie, które pokazuje, jak zmienia się ilość oferowana danego dobra w zależności od jego ceny.', page: 743 },
  { term: 'Plan popytu', definition: 'Zestawienie, które pokazuje, jak zmienia się wielkość zapotrzebowania na dane dobro w zależności od jego ceny.', page: 743 },
  { term: 'Płaca efektywnościowa', definition: 'Płaca przewyższająca poziom równowagi rynkowej, oferowana w celu zwiększenia wydajności pracownika.', page: 743 },
  { term: 'Płaca godziwa', definition: 'Stawka godzinowa ustalona na podstawie oszacowania wydatków zapewniających gospodarstwu domowemu poziom życia uznany za zadowalający.', page: 743 },
  { term: 'Płaca minimalna', definition: 'Najniższe wynagrodzenie, jakie pracodawca może zgodnie z prawem zaoferować pracownikowi.', page: 743 },
  { term: 'Podatek kwotowy', definition: 'Podatek od towarów i usług określony jako pewna stała kwota naliczana od każdej sprzedanej jednostki dobra.', page: 743 },
  { term: 'Podatek Pigou', definition: 'Podatek nakładany w celu skompensowania negatywnych efektów zewnętrznych.', page: 743 },
  { term: 'Podatek procentowy', definition: 'Podatek naliczany jako pewien procent od ceny dobra.', page: 743 },
  { term: 'Podatek progresywny', definition: 'Podatek procentowy, którego stawka zwiększa się wraz ze wzrostem dochodu.', page: 743 },
  { term: 'Podatek proporcjonalny (liniowy)', definition: 'Podatek procentowy, którego stawka jest jednakowa dla wszystkich podatników.', page: 743 },
  { term: 'Podatek regresywny', definition: 'Podatek procentowy, którego stawka maleje wraz ze wzrostem dochodu.', page: 743 },
  { term: 'Podatek ryczałtowy (pogłówny)', definition: 'Podatek płacony przez wszystkich w takiej samej kwocie.', page: 743 },
  { term: 'Podatki bezpośrednie', definition: 'Podatki naliczane od dochodu lub majątku.', page: 743 },
  { term: 'Podatki pośrednie', definition: 'Podatki naliczane od sprzedaży dóbr i usług.', page: 743 },
  { term: 'Podmiot ekonomiczny', definition: 'Osoba fizyczna, przedsiębiorstwo lub organizacja, która ma określony wpływ na gospodarkę.', page: 743 },
  { term: 'Pogoń za rentą', definition: 'Działania podejmowane przez jednostkę lub grupę w celu takiego ulokowania zasobów, by zapewnić sobie dochód ekonomiczny (rentę).', page: 743 },
  { term: 'Pokusa nadużycia', definition: 'Skłonność osoby, która nie podlega pełnej kontroli, do nieuczciwych lub niepożądanych zachowań.', page: 743 },
  { term: 'Pomoc społeczna', definition: 'Publiczny system świadczeń gwarantujący wsparcie materialne najbardziej potrzebującym.', page: 743 },
  { term: 'Poprawa w sensie Pareta', definition: 'Polepszenie sytuacji co najmniej jednego podmiotu rynkowego w wyniku pewnego działania bez pogorszenia sytuacji innego podmiotu.', page: 743 },
  { term: 'Popyt pochodny', definition: 'Popyt, którego wielkość zależy od podaży na innym rynku.', page: 743 },
  { term: 'Poziom życia', definition: 'Ilość dóbr i usług, które mogą nabyć mieszkańcy danego kraju, mierzona zazwyczaj jako realny (skorygowany o stopę inflacji) dochód na jednego mieszkańca.', page: 744 },
  { term: 'Pozycja względna', definition: 'Koncepcja, zgodnie z którą ludzie oceniają swoją sytuację względem pewnego punktu odniesienia, więc ich samopoczucie zależy od tego, z kim się porównują.', page: 744 },
  { term: 'Pozycjonalny efekt zewnętrzny', definition: 'Zakup lub decyzja, która wpływa na ocenę dobra pozycjonalnego przez konsumenta.', page: 744 },
  { term: 'Pozycjonalny wyścig zbrojeń', definition: 'Sytuacja, w której ludzie podejmują różne działania w celu zdobycia przewagi nad innymi, ale ich wysiłki wzajemnie się znoszą.', page: 744 },
  { term: 'Pozytywny efekt zewnętrzny', definition: 'Korzyść uzyskana przez osobę postronną wskutek czyjejś decyzji.', page: 744 },
  { term: 'Praca', definition: 'Wysiłek fizyczny i umysłowy człowieka potrzebny do wytwarzania dóbr i usług.', page: 744 },
  { term: 'Praca martwa', definition: 'Praca, która posłużyła do wytworzenia dóbr kapitałowych i surowców wykorzystywanych do produkcji dobra.', page: 744 },
  { term: 'Praca żywa', definition: 'Praca wykorzystywana bezpośrednio do produkcji dobra.', page: 744 },
  { term: 'Prawa autorskie', definition: 'Prawo własności osoby lub organizacji do stworzonego przez siebie dzieła, uniemożliwiające innym jego kopiowanie lub powielanie.', page: 744 },
  { term: 'Prawa własności', definition: 'Wyłączne prawo osoby fizycznej, grupy osób lub organizacji do dysponowania pewnym zasobem.', page: 744 },
  { term: 'Prawo podaży', definition: 'Jeśli inne czynniki są stałe, ilość oferowana dobra zwiększa się, gdy cena tego dobra rośnie.', page: 744 },
  { term: 'Prawo podaży i popytu', definition: 'Cena dobra dąży do poziomu, przy którym ilość oferowana zrównuje się z wielkością zapotrzebowania na to dobro.', page: 744 },
  { term: 'Prawo popytu', definition: 'Wielkość zapotrzebowania na dobro zmniejsza się, gdy cena tego dobra rośnie, przy założeniu stałości innych czynników (ceteris paribus).', page: 744 },
  { term: 'Problem gapowicza', definition: 'Zjawisko polegające na tym, że ktoś korzysta z pewnego dobra, ale za to nie płaci.', page: 744 },
  { term: 'Proces negocjacji', definition: 'Uzgadnianie warunków wymiany przez dwa zainteresowane podmioty rynkowe o sprzecznych celach.', page: 744 },
  { term: 'Produkt krajowy brutto per capita (na jednego mieszkańca)', definition: 'Wartość rynkowa wszystkich dóbr i usług wytworzonych w kraju w danym okresie podzielona przez liczbę mieszkańców.', page: 744 },
  { term: 'Produkt krańcowy', definition: 'Przyrost wielkości produkcji uzyskany w wyniku zwiększenia nakładu czynnika produkcji o jednostkę.', page: 744 },
  { term: 'Produkt krańcowy pracy', definition: 'Wzrost wielkości produkcji wynikający ze zwiększenia nakładu pracy o jednostkę.', page: 745 },
  { term: 'Próg ubóstwa', definition: 'Ustalony przez państwo poziom dochodów, poniżej którego rodzinę uznaje się za żyjącą w ubóstwie (w Europie za ten poziom przyjmuje się 60% mediany dochodów).', page: 745 },
  { term: 'Pryncypał', definition: 'Osoba, która zleca innej osobie, zwanej agentem, pewne zadanie.', page: 745 },
  { term: 'Prywatyzacja', definition: 'Przekazanie mienia państwowego w ręce prywatne.', page: 745 },
  { term: 'Przeciętna stopa podatkowa', definition: 'Całkowita kwota zapłaconych podatków podzielona przez dochód całkowity.', page: 745 },
  { term: 'Przeciętny koszt całkowity', definition: 'Koszt całkowity podzielony przez wielkość produkcji.', page: 745 },
  { term: 'Przeciętny koszt stały', definition: 'Koszty stałe podzielone przez wielkość produkcji.', page: 745 },
  { term: 'Przeciętny koszt zmienny', definition: 'Koszty zmienne podzielone przez wielkość produkcji.', page: 745 },
  { term: 'Przewaga absolutna', definition: 'Przewaga wynikająca z porównania nakładów ponoszonych przez różnych producentów na wytworzenie takiej samej ilości dobra.', page: 745 },
  { term: 'Przewaga komparatywna', definition: 'Przewaga wynikająca z porównania kosztów alternatywnych ponoszonych przez producentów; producent ma przewagę komparatywną w zakresie wytwarzania pewnego dobra, jeśli ponosi niższy koszt alternatywny niż inni producenci tego dobra.', page: 745 },
  { term: 'Przewaga konkurencyjna', definition: 'Przewaga nad rywalami uzyskana przez przedsiębiorstwo dzięki wykorzystaniu jakiegoś wyjątkowego i trudnego do skopiowania atutu.', page: 745 },
  { term: 'Racjonalne zachowanie', definition: 'Domniemana zdolność ludzi do dokonywania konsekwentnych wyborów między alternatywnymi rozwiązaniami.', page: 745 },
  { term: 'Reguła maksyminu', definition: 'Zasada, zgodnie z którą państwo powinno dążyć do maksymalizacji dobrobytu najgorzej sytuowanego członka społeczeństwa.', page: 745 },
  { term: 'Renta ekonomiczna', definition: 'Nadwyżka dochodu generowanego przez czynnik produkcji ponad odpowiadający mu dochód transferowy.', page: 745 },
  { term: 'Rozkład ciężaru opodatkowania', definition: 'Proporcje podziału ciężaru opodatkowania między uczestników rynku.', page: 745 },
  { term: 'Równowaga Nasha', definition: 'Sytuacja, w której współzależne podmioty rynkowe wybierają najlepszą dla siebie strategię, biorąc pod uwagę strategie wybrane przez innych.', page: 745 },
  { term: 'Równowaga ogólna', definition: 'Koncepcja, zgodnie z którą wszystkie rynki w gospodarce znajdują się w stanie równowagi, a miliony indywidualnych decyzji w połączeniu doprowadzają do zrównoważenia podaży i popytu, skutkując efektywną alokacją zasobów.', page: 745 },
  { term: 'Różnicowanie cen', definition: 'Sprzedaż takiego samego dobra różnym klientom po różnych cenach.', page: 745 },
  { term: 'Rynek', definition: 'Grupa nabywców i sprzedawców określonego dobra lub usługi.', page: 745 },
  { term: 'Rynek konkurencyjny', definition: 'Rynek, na którym działa wielu nabywców i wielu sprzedawców, więc każdy z nich pojedynczo ma znikomy wpływ na cenę rynkową.', page: 746 },
  { term: 'Rynek kontestowalny', definition: 'Rynek, na którym nie ma żadnych ograniczeń ani kosztów związanych z wejściem lub wyjściem.', page: 746 },
  { term: 'Rzadkość zasobów', definition: 'Właściwość zasobów polegająca na tym, że ich ilość jest ograniczona.', page: 746 },
  { term: 'Satysfakcjonalista', definition: 'Osoba podejmująca decyzje z myślą o uzyskaniu zadowalającego, a nie najlepszego rezultatu.', page: 746 },
  { term: 'Sądy normatywne', definition: 'Stwierdzenia wskazujące, jak świat powinien wyglądać.', page: 746 },
  { term: 'Sądy pozytywne', definition: 'Stwierdzenia opisujące świat takim, jaki jest.', page: 746 },
  { term: 'Scenariusz alternatywny', definition: 'Symulacja pokazująca, co by się stało, gdyby pewne zdarzenie nie miało miejsca.', page: 746 },
  { term: 'Segment rynku', definition: 'Grupa klientów o podobnych nawykach zakupowych lub cechach.', page: 746 },
  { term: 'Sektor prywatny', definition: 'Część gospodarki, w której wszelka działalność jest finansowana i zarządzana przez osoby prywatne.', page: 746 },
  { term: 'Sektor publiczny', definition: 'Część gospodarki, w której wszelka działalność jest finansowana i zarządzana przez państwo, a oferowane dobra i usługi służą całemu społeczeństwu.', page: 746 },
  { term: 'Siła rynkowa', definition: 'Zdolność jednego lub niewielkiej grupy podmiotów ekonomicznych do wywierania istotnego wpływu na ceny lub wielkość produkcji.', page: 746 },
  { term: 'Skala efektywna produkcji', definition: 'Wielkość produkcji, przy której przeciętny koszt całkowity jest najmniejszy.', page: 746 },
  { term: 'Skłonność do płacenia', definition: 'Maksymalna kwota, jaką nabywca chce zapłacić za dobro.', page: 746 },
  { term: 'Społecznie niezbędny czas pracy', definition: 'Ilość pracy potrzebna przy przeciętnej wydajności do wytworzenia danego towaru.', page: 746 },
  { term: 'Sprawiedliwość', definition: 'Uczciwy podział korzyści ekonomicznych między członków społeczeństwa.', page: 746 },
  { term: 'Sprawiedliwość pionowa', definition: 'Koncepcja, według której podatnicy o większej zdolności do płacenia powinni płacić wyższe podatki.', page: 746 },
  { term: 'Sprawiedliwość pozioma', definition: 'Koncepcja, według której podatnicy o podobnej zdolności do płacenia powinni płacić jednakowe podatki.', page: 746 },
  { term: 'Stałe przychody ze skali', definition: 'Zjawisko polegające na tym, że zmiana wielkości produkcji nie ma wpływu na długookresowy przeciętny koszt całkowity.', page: 746 },
  { term: 'Statyczna analiza porównawcza', definition: 'Porównywanie dwóch stanów równowagi statycznej.', page: 746 },
  { term: 'Stopa ubóstwa', definition: 'Odsetek gospodarstw domowych, których dochody nie przekraczają poziomu nazywanego progiem ubóstwa.', page: 746 },
  { term: 'Strajk', definition: 'Forma protestu pracowników polegająca na przerwaniu pracy.', page: 747 },
  { term: 'Strategia cen drapieżnych (niszczycielskich)', definition: 'Zachowanie polegające na tymczasowym obniżeniu ceny poniżej kosztu przeciętnego w celu wyparcia istniejących konkurentów z rynku lub zniechęcenia nowych konkurentów do wejścia na rynek.', page: 747 },
  { term: 'Strategia dominująca', definition: 'Strategia, która jest najlepsza dla gracza niezależnie od tego, jakie strategie wybiorą pozostali gracze.', page: 747 },
  { term: 'Subsydiowanie krzyżowe', definition: 'Taktyka polegająca na utrzymywaniu niskiej ceny na pewien produkt w celu odstraszenia konkurencji i pokrywaniu wynikających stąd strat z zysku osiąganego na innych produktach.', page: 747 },
  { term: 'Subwencja', definition: 'Suma pieniędzy przekazywana przez państwo nabywcom lub sprzedawcom po to, by zwiększyć dochody nabywców lub obniżyć koszty sprzedawców, a tym samym poprawić ich sytuację ekonomiczną lub zwiększyć konsumpcję.', page: 747 },
  { term: 'Suma wydatków', definition: 'Łączna kwota zapłacona przez nabywców, liczona jako iloczyn ceny i zakupionej ilości dobra.', page: 747 },
  { term: 'Sygnalizacja', definition: 'Działania podejmowane przez podmiot posiadający pewne informacje w celu ich wiarygodnego ujawnienia innym podmiotom.', page: 747 },
  { term: 'Synergia', definition: 'Zjawisko polegające na tym, że działając wspólnie, przedsiębiorstwa osiągają lepsze wyniki niż osobno.', page: 747 },
  { term: 'System ekonomiczny', definition: 'Sposób organizacji i alokacji zasobów w celu zaspokojenia potrzeb obywateli.', page: 747 },
  { term: 'System kapitalistyczny', definition: 'System ekonomiczny oparty na prywatnej własności czynników produkcji oraz wymianie wytworzonych dóbr i usług na zasadzie mechanizmu cenowego, gdzie działalność wytwórcza jest przede wszystkim nastawiona na zysk.', page: 747 },
  { term: 'Teoria dochodu permanentnego', definition: 'Teoria, zgodnie z którą ludzie dostosowują poziom konsumpcji do przewidywanego przeciętnego dochodu długookresowego.', page: 747 },
  { term: 'Teoria gier', definition: 'Narzędzie umożliwiające badanie zachowań ludzi w sytuacjach wymagających myślenia strategicznego.', page: 747 },
  { term: 'Teoria perspektywy', definition: 'Teoria, zgodnie z którą ludzie przypisują różne wartości zyskom i stratom w zależności od punktu odniesienia.', page: 747 },
  { term: 'Teoria użyteczności oczekiwanej', definition: 'Koncepcja, zgodnie z którą nabywcy potrafią uszeregować możliwości wyboru według stopnia zbieżności ze swoimi preferencjami.', page: 747 },
  { term: 'Teoria wyboru publicznego', definition: 'Dziedzina wiedzy poświęcona analizie postępowania administracji publicznej oraz zachowań obywateli w relacjach z administracją publiczną.', page: 747 },
  { term: 'Tragedia wspólnego pastwiska', definition: 'Koncepcja wyjaśniająca, dlaczego zasoby wspólne są wykorzystywane w większym stopniu, niż jest to wskazane z punktu widzenia całego społeczeństwa.', page: 747 },
  { term: 'Twierdzenie Coase’a', definition: 'Twierdzenie, które głosi, że jeśli podmioty prywatne mają możliwość negocjowania sposobu alokacji zasobów, nie ponosząc przy tym żadnych kosztów, to są w stanie samodzielnie uporać się z problemem efektów zewnętrznych.', page: 748 },
  { term: 'Ubóstwo bezwzględne', definition: 'Sytuacja, w której ludzie są pozbawieni dostępu do podstawowych dóbr niezbędnych do życia: jedzenia, odzieży i schronienia.', page: 748 },
  { term: 'Ubóstwo względne', definition: 'Sytuacja, w której ludzie żyją poniżej standardów uznawanych w danym społeczeństwie za zadowalające.', page: 748 },
  { term: 'Udział w rynku', definition: 'Udział przedsiębiorstwa w sprzedaży ogółem na danym rynku.', page: 748 },
  { term: 'Ujemny podatek dochodowy', definition: 'Metoda naliczania podatku, w przypadku której gospodarstwa domowe o niskich dochodach, zamiast płacić podatek, otrzymują dopłatę.', page: 748 },
  { term: 'Uogólnienie', definition: 'Formułowanie ogólnych koncepcji lub objaśnień poprzez wnioskowanie oparte na konkretnych wystąpieniach pewnego zdarzenia lub zachowania.', page: 748 },
  { term: 'Utarg całkowity', definition: 'Łączna kwota uzyskana przez sprzedawców, którą oblicza się jako iloczyn ceny i sprzedanej ilości dobra.', page: 748 },
  { term: 'Utarg krańcowy', definition: 'Zmiana utargu całkowitego w wyniku zwiększenia sprzedaży o jednostkę.', page: 748 },
  { term: 'Utarg przeciętny', definition: 'Utarg całkowity podzielony przez wielkość sprzedaży.', page: 748 },
  { term: 'Utylitaryzm', definition: 'Nurt filozofii politycznej, zgodnie z którym państwo powinno prowadzić politykę ukierunkowaną na maksymalizację użyteczności całkowitej osiąganej przez wszystkich członków społeczeństwa.', page: 748 },
  { term: 'Użyteczność', definition: 'Zadowolenie płynące z konsumpcji określonej ilości produktu.', page: 748 },
  { term: 'Użyteczność całkowita', definition: 'Zadowolenie płynące ze skonsumowania określonej ilości produktu.', page: 748 },
  { term: 'Użyteczność krańcowa', definition: 'Przyrost użyteczności całkowitej w wyniku skonsumowania dodatkowej jednostki danego produktu.', page: 748 },
  { term: 'Wartość', definition: 'Korzyść z posiadania pewnej rzeczy, która polega na zadowoleniu płynącym z jej skonsumowania i znajduje odzwierciedlenie w gotowości do zapłacenia za tę rzecz.', page: 748 },
  { term: 'Wartość produktu krańcowego', definition: 'Iloczyn produktu krańcowego czynnika produkcji i ceny rynkowej dobra.', page: 748 },
  { term: 'Wewnętrzne korzyści skali', definition: 'Korzyści związane z dużą skalą produkcji pojawiające się w wyniku rozwoju przedsiębiorstwa.', page: 748 },
  { term: 'Wielkość zapotrzebowania', definition: 'Ilość dobra, jaką kupujący chcą i są w stanie kupić przy danej cenie.', page: 748 },
  { term: 'Wnioskowanie', definition: 'Formułowanie spostrzeżeń lub objaśnień w drodze rozumowania lub na podstawie dostępnych danych.', page: 748 },
  { term: 'Wskaźnik koncentracji', definition: 'Udział określonej liczby dostawców w łącznych obrotach na rynku.', page: 749 },
  { term: 'Współczynnik Giniego', definition: 'Miara stopnia nierówności dochodowej.', page: 749 },
  { term: 'Wybór międzyokresowy', definition: 'Sytuacja, w której dzisiejsze decyzje mogą mieć wpływ na możliwości wyboru dostępne w późniejszym czasie.', page: 749 },
  { term: 'Wydajność', definition: 'Przeciętna ilość dóbr i usług wytwarzana przez pracownika lub czynnik produkcji w jednostce czasu.', page: 749 },
  { term: 'Wzrost gospodarczy', definition: 'Wzrost ilości dóbr i usług wytwarzanych przez gospodarkę w pewnym przedziale czasu.', page: 749 },
  { term: 'Zasada korzyści', definition: 'Koncepcja, zgodnie z którą ludzie powinni płacić podatki w wysokości uzależnionej od tego, w jakim zakresie korzystają ze świadczeń zapewnionych przez państwo.', page: 749 },
  { term: 'Zasada zdolności do płacenia', definition: 'Koncepcja, zgodnie z którą ciężar podatku powinien być dostosowany do możliwości finansowych podatnika.', page: 749 },
  { term: 'Zasiłek rzeczowy', definition: 'Pomoc dla ludzi biednych przekazywana w postaci dóbr i usług, a nie w formie pieniężnej.', page: 749 },
  { term: 'Zasoby wspólne', definition: 'Dobra, które stanowią przedmiot rywalizacji, ale nie podlegają zastrzeżeniu dostępu.', page: 749 },
  { term: 'Zawodność państwa', definition: 'Zjawisko polegające na zakłóceniu przez czynniki polityczne procesu podejmowania decyzji w taki sposób, że jego rezultaty nie idą w parze z efektywnością ekonomiczną.', page: 749 },
  { term: 'Zawodność rynku', definition: 'Sytuacja, w której rynek nie zapewnia efektywnej alokacji zasobów.', page: 749 },
  { term: 'Zbędna strata społeczna', definition: 'Obniżenie nadwyżki całkowitej spowodowane zakłóceniem funkcjonowania rynku, np. przez podatek.', page: 749 },
  { term: 'Zbiór wariantów wyboru', definition: 'Wszystkie dostępne opcje rozdysponowania dochodu przez konsumenta.', page: 749 },
  { term: 'Zewnętrzne korzyści skali', definition: 'Atuty produkcji na dużą skalę wynikające z rozwoju i koncentracji geograficznej branży.', page: 749 },
  { term: 'Ziemia', definition: 'Całość zasobów naturalnych naszej planety.', page: 749 },
  { term: 'Zmiany krańcowe', definition: 'Niewielkie, stopniowe zmiany przyjętego planu działania.', page: 749 },
  { term: 'Zmienna egzogeniczna', definition: 'Zmienna, której wartość jest ustalana poza modelem.', page: 749 },
  { term: 'Zmienna endogeniczna', definition: 'Zmienna, której wartość jest ustalana w ramach modelu.', page: 749 },
  { term: 'Zmowa', definition: 'Porozumienie między przedsiębiorstwami działającymi na tym samym rynku, dotyczące wielkości produkcji lub ceny.', page: 749 },
  { term: 'Zmowa milcząca', definition: 'Sytuacja, w której ograniczenie konkurencji wynika stąd, że przedsiębiorstwa, podejmując decyzje, uwzględniają występującą między nimi współzależność.', page: 750 },
  { term: 'Zróżnicowanie kompensacyjne', definition: 'Różnica w wysokości płac, która wynika z potrzeby wyrównania pozafinansowych różnic między poszczególnymi zawodami.', page: 750 },
  { term: 'Związek zawodowy', definition: 'Zrzeszenie pracowników, które prowadzi z pracodawcami negocjacje w sprawie płac i warunków pracy.', page: 750 },
  { term: 'Zysk ekonomiczny', definition: 'Utarg całkowity pomniejszony o koszt całkowity, obejmujący koszty jawne i ukryte.', page: 750 },
  { term: 'Zysk księgowy', definition: 'Utarg całkowity pomniejszony o całkowity koszt jawny.', page: 750 },
  { term: 'Zysk nadzwyczajny', definition: 'Nadwyżka zysku ponad zysk normalny.', page: 750 },
  { term: 'Zysk normalny', definition: 'Minimalna kwota niezbędna do utrzymania obecnego sposobu wykorzystania czynników produkcji.', page: 750 }
];

// Jawne przypisania pojęć ze słownika do rozdziałów, w których są one
// wprowadzane lub omawiane zasadniczo. Nie należy zastępować tej mapy
// dopasowaniem tekstowym: podobne słowa występują w wielu rozdziałach.
const conceptChapterAssignments = Object.freeze(Object.fromEntries([
  [1, [
    'Aktywność gospodarcza', 'Barter', 'Ekonomia', 'Gospodarka',
    'Gospodarka planowa', 'Gospodarka rynkowa', 'Inflacja', 'Instytucje',
    'Kompromis', 'Makroekonomia', 'Mikroekonomia', 'Podmiot ekonomiczny',
    'Poziom życia', 'Produkt krajowy brutto per capita (na jednego mieszkańca)',
    'Rzadkość zasobów', 'System ekonomiczny',
    'System kapitalistyczny', 'Wydajność', 'Wzrost gospodarczy',
    'Zmiany krańcowe'
  ]],
  [2, [
    'Ceteris paribus', 'Ekonomia heterodoksyjna', 'Falsyfikowalność',
    'Hipoteza', 'Sądy normatywne', 'Sądy pozytywne',
    'Scenariusz alternatywny', 'Statyczna analiza porównawcza',
    'Uogólnienie', 'Wnioskowanie', 'Zmienna egzogeniczna',
    'Zmienna endogeniczna'
  ]],
  [3, [
    'Cena równowagi (cena rynkowa)', 'Dobra komplementarne',
    'Dobra substytucyjne', 'Dobro niższego rzędu', 'Dobro normalne',
    'Ilość oferowana', 'Ilość równowagi', 'Krzywa podaży',
    'Krzywa popytu', 'Nadwyżka', 'Niedobór', 'Plan podaży',
    'Plan popytu', 'Prawo podaży', 'Prawo podaży i popytu',
    'Prawo popytu', 'Rynek', 'Rynek konkurencyjny',
    'Wielkość zapotrzebowania'
  ]],
  [4, [
    'Elastyczność', 'Elastyczność cenowa podaży',
    'Elastyczność cenowa popytu', 'Elastyczność dochodowa popytu',
    'Mieszana elastyczność cenowa popytu', 'Suma wydatków'
  ]],
  [5, [
    'Dobra doskonale komplementarne', 'Dobra doskonale substytucyjne',
    'Dobro Giffena', 'Efekt dochodowy', 'Efekt kontekstu',
    'Efekt substytucyjny', 'Heurystyki', 'Krańcowa stopa substytucji',
    'Krzywa cena-konsumpcja', 'Krzywa Engla', 'Krzywa obojętności',
    'Malejąca użyteczność krańcowa', 'Ograniczenie budżetowe',
    'Praca martwa', 'Praca żywa', 'Społecznie niezbędny czas pracy',
    'Teoria perspektywy', 'Teoria użyteczności oczekiwanej',
    'Użyteczność', 'Użyteczność całkowita', 'Użyteczność krańcowa',
    'Wartość', 'Zbiór wariantów wyboru'
  ]],
  [6, [
    'Długi okres', 'Funkcja produkcji', 'Korzyści (ekonomia) skali',
    'Koszt', 'Koszt krańcowy', 'Koszty jawne', 'Koszty stałe',
    'Koszty ukryte', 'Koszty utopione', 'Koszty zmienne', 'Krótki okres',
    'Malejąca wydajność krańcowa', 'Niekorzyści (dysekonomia) skali',
    'Produkt krańcowy', 'Przeciętny koszt całkowity',
    'Przeciętny koszt stały', 'Przeciętny koszt zmienny',
    'Skala efektywna produkcji', 'Stałe przychody ze skali',
    'Utarg całkowity', 'Utarg krańcowy', 'Utarg przeciętny',
    'Wewnętrzne korzyści skali', 'Zewnętrzne korzyści skali',
    'Zysk ekonomiczny', 'Zysk księgowy', 'Zysk nadzwyczajny',
    'Zysk normalny'
  ]],
  [7, [
    'Dobrobyt obiektywny', 'Dobrobyt subiektywny', 'Efektywność',
    'Efektywność alokacyjna', 'Ekonomia dobrobytu',
    'Funkcja dobrobytu społecznego', 'Nadwyżka całkowita',
    'Nadwyżka konsumenta', 'Nadwyżka producenta',
    'Poprawa w sensie Pareta', 'Równowaga ogólna',
    'Skłonność do płacenia', 'Sprawiedliwość', 'Zawodność rynku'
  ]],
  [8, [
    'Cena maksymalna', 'Cena minimalna', 'Podatek kwotowy',
    'Podatek procentowy', 'Rozkład ciężaru opodatkowania', 'Subwencja'
  ]],
  [9, [
    'Krańcowa stopa podatkowa', 'Podatek progresywny',
    'Podatek proporcjonalny (liniowy)', 'Podatek regresywny',
    'Podatek ryczałtowy (pogłówny)', 'Podatki bezpośrednie',
    'Podatki pośrednie', 'Przeciętna stopa podatkowa',
    'Sprawiedliwość pionowa', 'Sprawiedliwość pozioma',
    'Zasada korzyści', 'Zasada zdolności do płacenia',
    'Zbędna strata społeczna'
  ]],
  [10, [
    'Analiza kosztów i korzyści', 'Dobra klubowe', 'Dobra prywatne',
    'Dobra publiczne', 'Dobra społecznie niepożądane',
    'Dobra społecznie pożądane', 'Dobro rywalizacyjne',
    'Dobro zastrzegalne', 'Problem gapowicza',
    'Tragedia wspólnego pastwiska', 'Zasoby wspólne'
  ]],
  [11, [
    'Efekt racjonalnej ignorancji', 'Efekt wąskich interesów',
    'Efekt zewnętrzny', 'Interes publiczny',
    'Internalizacja efektu zewnętrznego',
    'Koalicja koniunkturalna', 'Koszt krańcowy redukcji zanieczyszczeń',
    'Koszty transakcyjne', 'Kumoterstwo',
    'Negatywny efekt zewnętrzny', 'Podatek Pigou', 'Pogoń za rentą',
    'Pozycja względna', 'Pozycjonalny efekt zewnętrzny',
    'Pozycjonalny wyścig zbrojeń', 'Pozytywny efekt zewnętrzny',
    'Prawa własności', 'Proces negocjacji', 'Sektor prywatny',
    'Sektor publiczny', 'Teoria wyboru publicznego',
    'Twierdzenie Coase’a', 'Zawodność państwa'
  ]],
  [12, [
    'Agent', 'Asymetria informacji', 'Cykl życia', 'Dochód permanentny',
    'Efekt posiadania', 'Negatywna selekcja', 'Odsiew',
    'Ograniczona racjonalność', 'Płaca godziwa', 'Pokusa nadużycia',
    'Pryncypał', 'Racjonalne zachowanie', 'Satysfakcjonalista',
    'Sygnalizacja', 'Teoria dochodu permanentnego', 'Wybór międzyokresowy'
  ]],
  [13, [
    'Izokoszta', 'Izokwanta produkcji',
    'Krańcowa stopa substytucji technicznej'
  ]],
  [14, [
    'Bariery wejścia', 'Doskonałe różnicowanie ceny',
    'Konkurencja niedoskonała', 'Monopol', 'Monopol naturalny',
    'Monopolista', 'Nieefektywność typu X', 'Patent', 'Prawa autorskie',
    'Prywatyzacja', 'Różnicowanie cen', 'Siła rynkowa', 'Synergia'
  ]],
  [15, [
    'Branding', 'Cena zaporowa', 'Ekonomia zakresu',
    'Konkurencja monopolistyczna', 'Mnożenie marek',
    'Przewaga konkurencyjna', 'Rynek kontestowalny', 'Segment rynku',
    'Strategia cen drapieżnych (niszczycielskich)',
    'Subsydiowanie krzyżowe'
  ]],
  [16, [
    'Dylemat więźnia', 'Gra pozycyjna', 'Kartel', 'Macierz wypłat',
    'Oligopol', 'Równowaga Nasha', 'Strategia dominująca',
    'Teoria gier', 'Udział w rynku', 'Wskaźnik koncentracji',
    'Zmowa', 'Zmowa milcząca'
  ]],
  [17, [
    'Dochód transferowy', 'Dyskryminacja', 'Kapitał', 'Kapitał ludzki',
    'Krańcowy przychód z zasobu', 'Monopson', 'Płaca efektywnościowa',
    'Popyt pochodny', 'Praca', 'Produkt krańcowy pracy',
    'Renta ekonomiczna', 'Strajk', 'Wartość produktu krańcowego',
    'Ziemia', 'Zróżnicowanie kompensacyjne', 'Związek zawodowy'
  ]],
  [18, [
    'Krzywa Lorenza', 'Liberalizm', 'Libertarianizm',
    'Mobilność ekonomiczna', 'Płaca minimalna', 'Pomoc społeczna',
    'Próg ubóstwa', 'Reguła maksyminu', 'Stopa ubóstwa',
    'Ubóstwo bezwzględne', 'Ubóstwo względne',
    'Ujemny podatek dochodowy', 'Utylitaryzm', 'Współczynnik Giniego',
    'Zasiłek rzeczowy'
  ]],
  [19, [
    'Arbitraż', 'Cena światowa', 'Cło', 'Eksport',
    'Granica możliwości produkcyjnych', 'Hipoteza Prebischa-Singera',
    'Import', 'Kontyngent przywozowy', 'Koszt alternatywny',
    'Przewaga absolutna', 'Przewaga komparatywna'
  ]]
].flatMap(([chapter, terms]) => terms.map(term => [term, chapter]))));
