const macroBookChapters = [
  { part: 'I', partTitle: 'Dane makroekonomiczne', number: 1, title: 'Pomiar dochodu narodowego', pages: '17–35', sections: ['Dochód narodowy i wydatki', 'Kalkulacja produktu krajowego brutto', 'Składniki PKB', 'Różnica między realnym a nominalnym PKB', 'Produkt krajowy brutto a dobrobyt'] },
  { part: 'I', partTitle: 'Dane makroekonomiczne', number: 2, title: 'Pomiar kosztów utrzymania', pages: '39–54', sections: ['Wskaźnik cen towarów i usług konsumpcyjnych', 'Problemy związane z pomiarem kosztów utrzymania', 'Deflator PKB a wskaźnik cen towarów i usług konsumpcyjnych', 'Korekta zmiennych ekonomicznych z tytułu inflacji', 'Realna i nominalna stopa procentowa'] },
  { part: 'II', partTitle: 'Gospodarka realna w długim okresie', number: 3, title: 'Produkcja i wzrost', pages: '61–94', sections: ['Wzrost gospodarczy na świecie', 'Teoria wzrostu gospodarczego', 'Znaczenie produkcyjności i warunkujące ją czynniki', 'Wzrost gospodarczy a polityka państwa', 'Znaczenie długofalowego wzrostu gospodarczego'] },
  { part: 'II', partTitle: 'Gospodarka realna w długim okresie', number: 4, title: 'Bezrobocie', pages: '95–127', sections: ['Definicja bezrobocia', 'Poszukiwanie pracy', 'Ustawowa płaca minimalna', 'Związki zawodowe i negocjacje zbiorowe', 'Teoria płac efektywnościowych', 'Koszty bezrobocia'] },
  { part: 'III', partTitle: 'Stopy procentowe, pieniądz i ceny w długim okresie', number: 5, title: 'Oszczędności, inwestycje i system finansowy', pages: '129–151', sections: ['Instytucje finansowe w gospodarce', 'Rynki finansowe', 'Pośrednicy finansowi', 'Oszczędności i inwestycje w systemie rachunków narodowych', 'Rynek funduszy pożyczkowych', 'Deficyt budżetowy i nadwyżka budżetowa'] },
  { part: 'III', partTitle: 'Stopy procentowe, pieniądz i ceny w długim okresie', number: 6, title: 'Podstawowe narzędzia finansów', pages: '155–173', sections: ['Wartość bieżąca', 'Kontrolowanie ryzyka', 'Awersja do ryzyka', 'Dywersyfikacja ryzyka indywidualnego', 'Zależność między ryzykiem a stopą zwrotu', 'Wycena aktywów'] },
  { part: 'III', partTitle: 'Stopy procentowe, pieniądz i ceny w długim okresie', number: 7, title: 'System pieniężny', pages: '176–212', sections: ['Czym jest pieniądz?', 'Funkcje pieniądza', 'Rola banków centralnych', 'Banki i podaż pieniądza', 'Kreacja pieniądza', 'Metody kontrolowania podaży pieniądza przez bank centralny', 'Zmiany w bankowości i kryzys finansowy'] },
  { part: 'III', partTitle: 'Stopy procentowe, pieniądz i ceny w długim okresie', number: 8, title: 'Wzrost ilości pieniądza i inflacja', pages: '214–236', sections: ['Klasyczna teoria inflacji', 'Poziom cen i wartość pieniądza', 'Klasyczna dychotomia i neutralność pieniądza', 'Szybkość obiegu pieniądza i równanie ilościowe', 'Podatek inflacyjny', 'Efekt Fishera', 'Koszty inflacji', 'Deflacja'] },
  { part: 'IV', partTitle: 'Makroekonomia gospodarki otwartej', number: 9, title: 'Makroekonomia gospodarki otwartej: podstawowe pojęcia', pages: '243–263', sections: ['Międzynarodowe przepływy dóbr i kapitału', 'Eksport, import i eksport netto', 'Odpływy kapitałowe netto', 'Oszczędności i inwestycje a przepływy międzynarodowe', 'Realne i nominalne kursy walutowe', 'Teoria parytetu siły nabywczej'] },
  { part: 'IV', partTitle: 'Makroekonomia gospodarki otwartej', number: 10, title: 'Makroekonomiczna teoria gospodarki otwartej', pages: '264–283', sections: ['Rynek funduszy pożyczkowych', 'Rynek walutowy', 'Stan równowagi w gospodarce otwartej', 'Odpływy kapitałowe netto jako łącznik między rynkami', 'Deficyt budżetowy państwa', 'Polityka handlowa', 'Ucieczka kapitału'] },
  { part: 'V', partTitle: 'Krótkookresowe wahania w gospodarce', number: 11, title: 'Cykle koniunkturalne', pages: '289–307', sections: ['Trend rozwojowy', 'Pojęcia związane z analizą danych', 'Rodzaje trendów', 'Procykliczne i antycykliczne zmiany danych makroekonomicznych', 'Zmienne jako wskaźniki', 'Przyczyny wahań koniunktury', 'Modele cykli koniunkturalnych'] },
  { part: 'V', partTitle: 'Krótkookresowe wahania w gospodarce', number: 12, title: 'Ekonomia keynesowska i model IS–LM', pages: '311–344', sections: ['Krzyż keynesowski', 'Wydatki planowane i rzeczywiste', 'Równowaga gospodarki', 'Efekt mnożnikowy', 'Krzywe IS i LM', 'Stan równowagi ogólnej w modelu IS–LM', 'Skutki polityki fiskalnej i pieniężnej', 'Od modelu IS–LM do zagregowanego popytu'] },
  { part: 'V', partTitle: 'Krótkookresowe wahania w gospodarce', number: 13, title: 'Zagregowany popyt i zagregowana podaż', pages: '348–377', sections: ['Trzy podstawowe fakty dotyczące wahań koniunktury', 'Podstawowy model wahań koniunktury', 'Krzywa zagregowanego popytu', 'Krzywa zagregowanej podaży', 'Długookresowy wzrost gospodarczy i inflacja', 'Skutki zmiany zagregowanego popytu', 'Skutki zmiany zagregowanej podaży', 'Nowa ekonomia keynesowska'] },
  { part: 'V', partTitle: 'Krótkookresowe wahania w gospodarce', number: 14, title: 'Wpływ polityki fiskalnej i pieniężnej na zagregowany popyt', pages: '382–400', sections: ['Jak polityka pieniężna wpływa na zagregowany popyt?', 'Teoria preferencji płynności', 'Zmiany podaży pieniądza', 'Rola stóp procentowych', 'Wpływ polityki fiskalnej na zagregowany popyt', 'Efekt wypierania', 'Rola państwa w stabilizowaniu gospodarki', 'Automatyczne mechanizmy stabilizujące'] },
  { part: 'V', partTitle: 'Krótkookresowe wahania w gospodarce', number: 15, title: 'Wybór między inflacją a bezrobociem w krótkim okresie', pages: '407–436', sections: ['Krzywa Phillipsa', 'Zagregowany popyt i podaż a krzywa Phillipsa', 'Wpływ oczekiwań na położenie krzywej Phillipsa', 'Długookresowa krzywa Phillipsa', 'Wpływ wstrząsów podażowych', 'Koszty tłumienia inflacji', 'Teoria racjonalnych oczekiwań', 'Polityka celu inflacyjnego'] },
  { part: 'V', partTitle: 'Krótkookresowe wahania w gospodarce', number: 16, title: 'Polityka podażowa', pages: '440–456', sections: ['Przesunięcie krzywej zagregowanej podaży', 'Instrumenty polityki podażowej', 'Rynkowe instrumenty polityki podażowej', 'Interwencyjne instrumenty polityki podażowej'] },
  { part: 'VI', partTitle: 'Makroekonomia międzynarodowa', number: 17, title: 'Wspólne obszary walutowe i europejska Unia Gospodarcza i Walutowa', pages: '463–488', sections: ['Euro', 'Jednolity rynek europejski i euro', 'Korzyści i koszty związane ze wspólną walutą', 'Teoria optymalnego obszaru walutowego', 'Czy Europa jest optymalnym obszarem walutowym?', 'Polityka fiskalna a wspólne obszary walutowe', 'Federalizm fiskalny', 'Pakt fiskalny'] },
  { part: 'VI', partTitle: 'Makroekonomia międzynarodowa', number: 18, title: 'Kryzys finansowy i problem długu publicznego', pages: '493–524', sections: ['Bańki inwestycyjne i spekulacja', 'Deregulacja rynków', 'Wzrost cen na rynku mieszkaniowym', 'Rynek subprime', 'Pęknięcie bańki', 'Na drodze do globalnej recesji', 'Rola banków centralnych', 'Kryzys zadłużenia publicznego', 'Deficyt strukturalny i cykliczny', 'Konsolidacja fiskalna'] }
];

const macroBookConcepts = [
  [1, 'Produkt krajowy brutto (PKB)', 'Wartość rynkowa wszystkich dóbr i usług finalnych wytworzonych w kraju w danym okresie.'],
  [1, 'Konsumpcja', 'Wydatki gospodarstw domowych na dobra i usługi z wyjątkiem zakupu nowych domów i mieszkań.'],
  [1, 'Inwestycje', 'Wydatki na zakup lub wytworzenie nieruchomości, maszyn, urządzeń, środków transportu i zapasów, w tym nowych mieszkań i domów.'],
  [1, 'Wydatki publiczne', 'Wydatki na zakup dóbr i usług przez instytucje rządowe i samorządowe.'],
  [1, 'Płatności transferowe', 'Płatności niezwiązane z zakupem dobra lub usługi.'],
  [1, 'Eksport netto', 'Różnica między wydatkami zagranicy na dobra krajowe a wydatkami krajowymi na dobra wytworzone za granicą.'],
  [1, 'Nominalny PKB', 'Wartość produkcji dóbr i usług w cenach bieżących.'],
  [1, 'Realny PKB', 'Wartość produkcji dóbr i usług skorygowana o efekt zmiany cen.'],
  [1, 'PKB w cenach bieżących lub rynkowych', 'PKB obliczony przez pomnożenie bieżącej produkcji dóbr i usług przez ich ceny w roku sprawozdawczym.'],
  [1, 'PKB w cenach stałych', 'PKB obliczony przy użyciu cen z wybranego roku bazowego, a więc skorygowany o efekt inflacji.'],
  [1, 'Deflator PKB', 'Wskaźnik poziomu cen obliczany jako stosunek nominalnego PKB do realnego PKB pomnożony przez 100.'],
  [1, 'Ujęcie łańcuchowe roczne', 'Metoda obliczania miar ilościowych PKB na bazie cen z roku poprzedniego.'],
  [1, 'Wartość dodana brutto', 'Wkład krajowych producentów, branż i sektorów w gospodarkę.'],

  [2, 'Koszty utrzymania', 'Wydatki potrzebne gospodarstwu domowemu do zapewnienia określonego poziomu życia.'],
  [2, 'Wskaźnik cen dóbr produkcyjnych (PPI)', 'Miara wartości koszyka dóbr i usług nabywanych przez przedsiębiorstwa.'],
  [2, 'Wskaźnik cen towarów i usług konsumpcyjnych (CPI)', 'Miara ogólnego poziomu cen płaconych przez przeciętnego konsumenta.'],
  [2, 'Indeksacja', 'Automatyczne korygowanie danej kwoty ze względu na inflację na mocy przepisów lub umowy.'],
  [2, 'Nominalna stopa procentowa', 'Stopa procentowa, według której naliczane są odsetki, nieskorygowana o wpływ inflacji.'],
  [2, 'Realna stopa procentowa', 'Nominalna stopa procentowa skorygowana o wpływ inflacji.'],
  [2, 'Płaca realna', 'Stawka wynagrodzenia skorygowana o stopę inflacji, obliczana jako stosunek płacy nominalnej do poziomu cen.'],
  [2, 'Stopa inflacji', 'Procentowa zmiana wskaźnika cen w stosunku do poprzedniego okresu.'],
  [2, 'Poziom cen', 'Wskaźnik informujący o średniej wysokości cen dóbr i usług w gospodarce w określonym momencie.'],

  [3, 'Efekt doganiania', 'Zjawisko polegające na tym, że kraje ubogie często odznaczają się szybszym wzrostem gospodarczym niż kraje bogate.'],
  [3, 'Drenaż mózgów', 'Emigracja dobrze wykształconych pracowników z krajów biednych do krajów bogatych.'],
  [3, 'Bezpośrednie inwestycje zagraniczne', 'Inwestycje rzeczowe, których właścicielem i zarządcą jest podmiot zagraniczny.'],
  [3, 'Portfelowe inwestycje zagraniczne', 'Inwestycje finansowane z funduszy zagranicznych, ale znajdujące się pod kontrolą podmiotów krajowych.'],
  [3, 'Teoria endogenicznego wzrostu gospodarczego', 'Teoria wiążąca długookresowy wzrost z wydajnością czynników produkcji i postępem technicznym.'],
  [3, 'Równowaga stanu ustalonego', 'Sytuacja, w której inwestycje zrównują się z amortyzacją, a stosunek kapitału do pracy nie ulega zmianie.'],
  [3, 'Twórcza destrukcja', 'Proces zastępowania istniejących technologii nowymi rozwiązaniami, które wymagają nowych umiejętności.'],
  [3, 'Wiedza technologiczna', 'Znajomość najlepszych metod wytwarzania dóbr i usług.'],
  [3, 'Zasoby naturalne', 'Wykorzystywane w produkcji zasoby pochodzące z przyrody, takie jak ziemia, woda i surowce mineralne.'],
  [3, 'Saldo migracji', 'Różnica między napływem a odpływem ludności z kraju.'],
  [3, 'Wskaźnik urodzeń', 'Liczba urodzonych dzieci w przeliczeniu na tysiąc mieszkańców.'],
  [3, 'Wskaźnik zgonów', 'Liczba zgonów w przeliczeniu na tysiąc mieszkańców.'],

  [4, 'Bezrobocie cykliczne', 'Odchylenie stopy bezrobocia od poziomu naturalnego.'],
  [4, 'Bezrobocie dobrowolne', 'Sytuacja, w której ludzie nie są zainteresowani dostępnymi ofertami pracy.'],
  [4, 'Bezrobocie frykcyjne', 'Bezrobocie wynikające z czasu potrzebnego na znalezienie pracy najlepiej odpowiadającej pracownikowi.'],
  [4, 'Bezrobocie przymusowe', 'Sytuacja, w której ludzie chcą pracować przy aktualnych stawkach płac, ale nie mogą znaleźć zatrudnienia.'],
  [4, 'Bezrobocie strukturalne', 'Bezrobocie wynikające z tego, że na niektórych rynkach jest zbyt mało miejsc pracy dla wszystkich poszukujących.'],
  [4, 'Bierni zawodowo', 'Osoby niezaliczane ani do pracujących, ani do bezrobotnych.'],
  [4, 'Gospodarka zleceniowa', 'Rynek pracy oparty na umowach krótkoterminowych, zerogodzinowych i jednorazowych zleceniach.'],
  [4, 'Naturalna stopa bezrobocia', 'Normalny poziom bezrobocia, wokół którego oscyluje faktyczna stopa bezrobocia.'],
  [4, 'Negocjacje zbiorowe', 'Proces uzgadniania warunków zatrudnienia między związkami zawodowymi a pracodawcami.'],
  [4, 'Niemobilność geograficzna', 'Trudność podjęcia pracy z powodu dojazdów lub przeprowadzki.'],
  [4, 'Niemobilność zawodowa', 'Trudność przestawienia się pracowników na wykonywanie innego zawodu.'],
  [4, 'Pełne zatrudnienie', 'Sytuacja, w której wszyscy chętni do pracy przy aktualnym poziomie płac mogą znaleźć zatrudnienie.'],
  [4, 'Poszukiwanie pracy', 'Proces przeglądania ofert pracy pod kątem własnych kwalifikacji i oczekiwań.'],
  [4, 'Stopa bezrobocia', 'Procentowy udział osób bezrobotnych w zasobie siły roboczej.'],
  [4, 'Stopień uzwiązkowienia', 'Procentowy udział członków związków zawodowych w ogólnej liczbie osób aktywnych zawodowo.'],
  [4, 'Ubezpieczenie od bezrobocia', 'Ubezpieczenie społeczne zapewniające środki na zasiłki dla osób, które utraciły pracę.'],
  [4, 'Wskaźnik aktywności zawodowej (lub ekonomicznej)', 'Procentowy udział osób aktywnych zawodowo w populacji dorosłych.'],
  [4, 'Zasób siły roboczej', 'Łączna liczba pracujących i bezrobotnych w gospodarce.'],

  [5, 'Akcja', 'Papier wartościowy stanowiący tytuł współwłasności przedsiębiorstwa.'],
  [5, 'Obligacja', 'Dłużny papier wartościowy.'],
  [5, 'Fundusz inwestycyjny', 'Instytucja sprzedająca jednostki uczestnictwa i inwestująca pozyskane środki w portfel akcji i obligacji.'],
  [5, 'Gospodarka finansowa', 'Działalność związana z kupnem i sprzedażą aktywów inwestycyjnych na rynkach finansowych.'],
  [5, 'Gospodarka realna', 'Działalność związana z wytwarzaniem towarów i usług.'],
  [5, 'System finansowy', 'Zbiór instytucji, które pomagają przełożyć oszczędności jednej grupy podmiotów na inwestycje innych.'],
  [5, 'Rynki finansowe', 'Instytucje finansowe, za których pośrednictwem oszczędzający mogą udostępniać pieniądze pożyczającym.'],
  [5, 'Pośrednicy finansowi', 'Instytucje, do których trafiają pieniądze oszczędzających, zanim zostaną przekazane pożyczającym.'],
  [5, 'Rynek funduszy pożyczkowych', 'Rynek, na którym oszczędzający oferują fundusze, a inwestorzy zgłaszają na nie zapotrzebowanie.'],
  [5, 'Elastyczność popytu i podaży względem stopy procentowej', 'Wrażliwość podaży i popytu na fundusze pożyczkowe na zmiany stopy procentowej.'],
  [5, 'Oszczędności narodowe (oszczędności)', 'Łączny dochód w gospodarce pomniejszony o wydatki konsumpcyjne i wydatki publiczne.'],
  [5, 'Oszczędności prywatne', 'Część dochodu pozostająca gospodarstwom domowym po podatkach i konsumpcji.'],
  [5, 'Oszczędności publiczne', 'Część dochodów podatkowych pozostająca państwu po opłaceniu wydatków publicznych.'],
  [5, 'Deficyt budżetowy', 'Sytuacja, w której dochody podatkowe nie wystarczają na pokrycie wydatków publicznych.'],
  [5, 'Nadwyżka budżetowa', 'Sytuacja, w której dochody podatkowe przewyższają wydatki publiczne.'],
  [5, 'Równowaga budżetowa', 'Sytuacja, w której dochody państwa są równe wydatkom państwa wraz z kosztami obsługi zadłużenia.'],
  [5, 'Swap ryzyka kredytowego', 'Instrument finansowy ubezpieczający posiadacza obligacji przed niewykonaniem zobowiązania przez dłużnika.'],
  [5, 'Równoległy system bankowy (shadow banking system)', 'Pośrednicy oferujący usługi bankowe, ale niepodlegający regulacjom obowiązującym banki.'],

  [6, 'Analiza fundamentalna', 'Analiza sprawozdań finansowych i perspektyw rozwojowych przedsiębiorstwa w celu określenia jego wartości.'],
  [6, 'Awersja do ryzyka', 'Niechęć do pozostawania w stanie niepewności.'],
  [6, 'Dywersyfikacja', 'Ograniczanie ryzyka przez zastąpienie jednego dużego źródła wieloma mniejszymi i niezależnymi źródłami.'],
  [6, 'Dźwignia finansowa (lewarowanie)', 'Pożyczanie pieniędzy na inwestycje finansowe o spodziewanej atrakcyjnej stopie zwrotu.'],
  [6, 'Efektywność informacyjna', 'Racjonalne uwzględnianie wszystkich dostępnych informacji.'],
  [6, 'Hipoteza efektywności rynku', 'Koncepcja, zgodnie z którą cena aktywów odzwierciedla wszystkie publicznie dostępne informacje o ich wartości.'],
  [6, 'Majątek', 'Łączne zasoby środków przechowywania wartości, w tym aktywów pieniężnych i niepieniężnych.'],
  [6, 'Płynność aktywów', 'Łatwość, z jaką składnik aktywów można zamienić na środek wymiany.'],
  [6, 'Procent składany', 'Zasada, według której naliczone odsetki powiększają kwotę będącą podstawą naliczania kolejnych odsetek.'],
  [6, 'Ryzyko', 'Prawdopodobieństwo wystąpienia zdarzenia powodującego straty finansowe lub inne szkody.'],
  [6, 'Ryzyko indywidualne (niesystematyczne)', 'Ryzyko dotyczące tylko jednego podmiotu ekonomicznego.'],
  [6, 'Ryzyko zagregowane', 'Ryzyko dotyczące w równym stopniu wszystkich podmiotów ekonomicznych.'],
  [6, 'Wartość bieżąca', 'Kwota, jaką należałoby zainwestować dziś, aby przy obecnych stopach uzyskać określoną sumę w przyszłości.'],
  [6, 'Wartość przyszła', 'Wartość, którą zainwestowana dziś suma osiągnie po określonym czasie przy danej stopie procentowej.'],

  [7, 'Bank centralny', 'Instytucja odpowiedzialna za regulowanie ilości pieniądza w gospodarce.'],
  [7, 'Bankowość detaliczna', 'Działalność obejmująca przyjmowanie depozytów i udzielanie kredytów gospodarstwom domowym oraz przedsiębiorstwom.'],
  [7, 'Bankowość hurtowa', 'Działalność związana z zarządzaniem finansami przedsiębiorstw i inwestowaniem w instrumenty finansowe.'],
  [7, 'Bezwarunkowe operacje rynku otwartego', 'Sprzedaż lub zakup aktywów niepieniężnych bez zobowiązania do późniejszej transakcji odwrotnej.'],
  [7, 'Gotówka', 'Banknoty i bilon znajdujące się w obiegu.'],
  [7, 'Jednostka rozliczeniowa', 'Miara służąca do wyrażania cen i zapisywania zobowiązań.'],
  [7, 'Operacje otwartego rynku', 'Transakcje kupna i sprzedaży aktywów niepieniężnych zawierane przez bank centralny z sektorem bankowym.'],
  [7, 'Pieniądz', 'Zbiór aktywów regularnie wykorzystywanych do kupowania dóbr i usług.'],
  [7, 'Pieniądz symboliczny (przymusowy)', 'Pieniądz pozbawiony wartości samoistnej, pełniący swoją funkcję na mocy obowiązujących przepisów.'],
  [7, 'Pieniądz towarowy', 'Pieniądz mający postać towaru o wartości samoistnej.'],
  [7, 'Podaż pieniądza', 'Ilość pieniądza dostępna w gospodarce.'],
  [7, 'Podwójna zbieżność potrzeb', 'Sytuacja, w której dwa podmioty oferują na wymianę coś, czego potrzebuje druga strona.'],
  [7, 'Polityka pieniężna', 'Działania banku centralnego służące regulowaniu podaży pieniądza.'],
  [7, 'Rynek pieniądza', 'Rynek międzybankowych pożyczek krótkoterminowych.'],
  [7, 'Standard (parytet) złota', 'System, w którym jednostka waluty odpowiada określonej ilości złota i może zostać na nie wymieniona.'],
  [7, 'Stopa dyskontowa (stopa funduszy federalnych)', 'Stopa oprocentowania krótkoterminowych pożyczek udzielanych przez Rezerwę Federalną bankom amerykańskim.'],
  [7, 'Stopa refinansowa', 'Stopa oprocentowania krótkoterminowych pożyczek udzielanych przez EBC bankom strefy euro.'],
  [7, 'Stopa repo', 'Stopa oprocentowania krótkoterminowych pożyczek udzielanych przez Bank Anglii bankom brytyjskim.'],
  [7, 'Środek przechowywania wartości', 'Coś, co pozwala przenieść bieżącą siłę nabywczą w przyszłość.'],
  [7, 'Środek wymiany', 'Coś, co nabywcy dają sprzedawcom w zamian za kupowane dobra lub usługi.'],
  [7, 'Transakcja z przyrzeczeniem odkupu', 'Sprzedaż aktywów, przy której sprzedający zobowiązuje się odkupić je po ustalonej cenie i w ustalonym terminie.'],
  [7, 'Wkłady płatne na żądanie', 'Środki na rachunkach bankowych dostępne w każdej chwili, na przykład kartą debetową.'],
  [7, 'Wymiana barterowa', 'Bezpośrednia wymiana jednych dóbr i usług na inne.'],
  [7, 'Zasób pieniądza', 'Ilość pieniądza krążąca w gospodarce.'],

  [8, 'Deflacja', 'Spadek poziomu cen w danym okresie, czyli ujemna inflacja.'],
  [8, 'Dezinflacja', 'Obniżenie stopy inflacji.'],
  [8, 'Efekt Fishera', 'Zmiana inflacji prowadzi do takiej samej, wyrażonej w punktach procentowych zmiany nominalnej stopy procentowej.'],
  [8, 'Hiperinflacja', 'Gwałtowny i przyspieszający wzrost cen, gdy miesięczna stopa inflacji przekracza 50%.'],
  [8, 'Ilościowa teoria pieniądza', 'Teoria, według której ilość pieniądza decyduje o poziomie cen, a jej tempo wzrostu o stopie inflacji.'],
  [8, 'Klasyczna dychotomia', 'Teoretyczny podział zmiennych ekonomicznych na nominalne i realne.'],
  [8, 'Cena względna', 'Cena określająca ilościowy stosunek wymiany jednego dobra na inne.'],
  [8, 'Koszt zdartych zelówek', 'Zasoby zużywane wskutek ograniczania podręcznych zasobów gotówki z obawy przed inflacją.'],
  [8, 'Koszty zmiany jadłospisów', 'Koszty zmiany cen.'],
  [8, 'Neutralność pieniądza', 'Brak wpływu zmian podaży pieniądza na zmienne realne.'],
  [8, 'Podatek inflacyjny', 'Dochód uzyskany przez państwo w wyniku kreacji pieniądza.'],
  [8, 'Realna podaż pieniądza', 'Stosunek nominalnej podaży pieniądza do poziomu cen, określający ilość dóbr możliwą do kupienia za dany zasób pieniądza.'],
  [8, 'Równanie ilościowe (M × V = P × Y)', 'Równanie łączące ilość pieniądza, szybkość jego obiegu i nominalną wartość produkcji.'],
  [8, 'Szybkość obiegu pieniądza', 'Częstotliwość, z jaką jednostka pieniądza jest używana do rozliczania transakcji.'],
  [8, 'Zmienne nominalne', 'Zmienne wyrażane w jednostkach pieniężnych.'],
  [8, 'Zmienne realne', 'Zmienne wyrażane w jednostkach fizycznych.'],

  [9, 'Aprecjacja waluty', 'Wzrost wartości waluty mierzony ilością waluty obcej, którą można za nią kupić.'],
  [9, 'Arbitraż', 'Transakcje wykorzystujące różnice cen tego samego dobra na różnych rynkach w celu osiągnięcia zysku.'],
  [9, 'Bilans handlu zagranicznego', 'Różnica między wartością eksportu i importu kraju, czyli eksport netto.'],
  [9, 'Bilans płatniczy', 'Oficjalne zestawienie międzynarodowych płatności z tytułu importu i eksportu towarów, usług oraz kapitału.'],
  [9, 'Deficyt handlowy', 'Nadwyżka importu nad eksportem.'],
  [9, 'Deprecjacja waluty', 'Spadek wartości waluty mierzony ilością waluty obcej, którą można za nią kupić.'],
  [9, 'Nadwyżka handlowa', 'Nadwyżka eksportu nad importem.'],
  [9, 'Nominalny kurs walutowy', 'Kurs, po którym można wymienić walutę jednego kraju na walutę innego kraju.'],
  [9, 'Odpływy kapitałowe netto', 'Różnica między zakupem aktywów zagranicznych przez podmioty krajowe a zakupem aktywów krajowych przez zagranicę.'],
  [9, 'Realny kurs walutowy', 'Stosunek wymiany dóbr i usług wytworzonych w jednym kraju na dobra i usługi wytworzone w innym kraju.'],
  [9, 'Teoria parytetu siły nabywczej', 'Teoria kursu walutowego, według której siła nabywcza jednostki waluty powinna być jednakowa we wszystkich krajach.'],
  [9, 'Zrównoważony bilans handlowy', 'Sytuacja, w której eksport i import mają jednakową wartość.'],

  [10, 'Polityka handlowa', 'Działania państwa bezpośrednio wpływające na ilość dóbr i usług eksportowanych lub importowanych.'],
  [10, 'Ucieczka kapitału', 'Nagły, znaczny spadek popytu na aktywa dostępne w danym kraju.'],

  [11, 'Amplituda', 'Różnica między szczytem a dnem cyklu koniunkturalnego.'],
  [11, 'Błądzenie losowe', 'Właściwość zmiennej polegająca na nieprzewidywalnych zmianach jej wartości.'],
  [11, 'Cykl koniunkturalny', 'Wahania koniunktury znajdujące odzwierciedlenie w stopie bezrobocia i wielkości produkcji.'],
  [11, 'Dno', 'Moment, w którym powiązane zmienne ekonomiczne wkraczają w fazę wzrostową.'],
  [11, 'Kryzys', 'Głęboka, długotrwała recesja.'],
  [11, 'Prawo Saya', 'Założenie, że produkcja jest źródłem popytu, a podaż tworzy własny popyt.'],
  [11, 'Recesja', 'Okres spadku dochodów realnych i rosnącego bezrobocia; statystycznie często dwa kolejne kwartały ujemnego wzrostu.'],
  [11, 'Regres', 'Spadek produkcji realnej w porównaniu z poprzednim okresem.'],
  [11, 'Szczyt', 'Moment, w którym powiązane zmienne ekonomiczne wkraczają w fazę spadkową.'],
  [11, 'Szereg czasowy', 'Uporządkowany chronologicznie ciąg obserwacji wartości zmiennej w kolejnych okresach.'],
  [11, 'Trend', 'Kierunek przebiegu szeregu czasowego w ujęciu długookresowym.'],
  [11, 'Trend deterministyczny', 'Trend, który niezależnie od przedziału czasu pozostaje wzrostowy albo spadkowy.'],
  [11, 'Trend stochastyczny', 'Trend, w ramach którego wartość zmiennej w kolejnych okresach zmienia się losowo.'],
  [11, 'Wielkie uspokojenie', 'Okres stabilizacji cechujący się niską inflacją, wysokim zatrudnieniem i stabilnym wzrostem.'],
  [11, 'Wskaźnik opóźniony', 'Wskaźnik zmieniający się w następstwie zmiany koniunktury.'],
  [11, 'Wskaźnik wyprzedzający', 'Wskaźnik mogący służyć do przewidywania zmian koniunktury.'],
  [11, 'Wskaźnik zbieżny', 'Wskaźnik zmieniający się wraz z aktualnym stanem koniunktury.'],
  [11, 'Zmienna antycykliczna', 'Zmienna ujemnie skorelowana z PKB.'],
  [11, 'Zmienna niestacjonarna', 'Zmienna, której średnia w długim okresie rośnie albo maleje.'],
  [11, 'Zmienna procykliczna', 'Zmienna dodatnio skorelowana z PKB.'],
  [11, 'Zmienna stacjonarna', 'Zmienna, która w długim okresie cechuje się stałą średnią.'],

  [12, 'Efekt mnożnikowy', 'Dodatkowe zmiany popytu zagregowanego, gdy wzrost dochodów prowadzi do kolejnych wydatków konsumpcyjnych.'],
  [12, 'Krańcowa skłonność do konsumpcji', 'Odsetek dodatkowego dochodu przeznaczany przez gospodarstwo domowe na konsumpcję.'],
  [12, 'Krańcowa skłonność do oszczędzania', 'Odsetek dodatkowego dochodu przeznaczany przez gospodarstwo domowe na oszczędności.'],
  [12, 'Luka deflacyjna lub produktowa', 'Dodatnia różnica między produkcją pełnego zatrudnienia a wydatkami rzeczywistymi odpowiadającymi tej produkcji.'],
  [12, 'Luka inflacyjna', 'Ujemna różnica między produkcją pełnego zatrudnienia a wydatkami rzeczywistymi odpowiadającymi tej produkcji.'],
  [12, 'Popyt efektywny', 'Ilość dóbr i usług, którą ludzie przy różnych cenach chcą, mogą i faktycznie kupują.'],
  [12, 'Wydatki autonomiczne', 'Wydatki niezależne od wielkości dochodu lub produkcji.'],
  [12, 'Wydatki, oszczędności lub inwestycje planowane', 'Zamierzone efekty działań przedsiębiorstw i gospodarstw domowych.'],
  [12, 'Wydatki, oszczędności lub inwestycje rzeczywiste', 'Faktyczne efekty działań przedsiębiorstw i gospodarstw domowych.'],

  [13, 'Inflacja kosztowa', 'Przyspieszenie inflacji wynikające ze wzrostu kosztów przedsiębiorstw i przerzucenia ich na konsumentów.'],
  [13, 'Krzywa podaży zagregowanej', 'Krzywa określająca ilość dóbr i usług wytwarzaną przez przedsiębiorstwa przy danym poziomie cen.'],
  [13, 'Krzywa popytu zagregowanego', 'Krzywa określająca ilość dóbr i usług, którą gospodarka chce nabyć przy danym poziomie cen.'],
  [13, 'Model popytu zagregowanego i podaży zagregowanej', 'Model objaśniający krótkookresowe wahania aktywności wokół długookresowego trendu.'],
  [13, 'Naturalny poziom produkcji', 'Produkcja przy pełnym wykorzystaniu dostępnych czynników i naturalnym poziomie bezrobocia.'],
  [13, 'Prawo Okuna', 'Prawo mówiące, że stabilizacja bezrobocia wymaga wzrostu realnego PKB zbliżonego do wzrostu potencjalnego.'],
  [13, 'Stagflacja', 'Jednoczesny spadek produkcji i wzrost cen.'],
  [13, 'Synteza neoklasyczna', 'Teoria zakładająca powolne dostosowanie cen i płac oraz długookresowy powrót do zasad ekonomii klasycznej.'],
  [13, 'Wstrząs podażowy', 'Zdarzenie zmieniające koszty produkcji i ceny, przesuwające zagregowaną podaż oraz krzywą Phillipsa.'],

  [14, 'Automatyczne mechanizmy stabilizujące', 'Zmiany fiskalne zachodzące bez nowych decyzji władz i pobudzające popyt zagregowany w recesji.'],
  [14, 'Efekt substytucji międzyokresowej', 'Wpływ zmian stopy procentowej na decyzje dotyczące konsumpcji i oszczędności.'],
  [14, 'Efekt wypierania', 'Obniżenie poziomu inwestycji wskutek wzrostu długu publicznego.'],
  [14, 'Ograniczona swoboda', 'Zasada, według której politycy mają narzucony cel, lecz mogą elastycznie reagować na wstrząsy.'],
  [14, 'Teoria preferencji płynności', 'Teoria Keynesa, według której stopa procentowa równoważy podaż pieniądza i popyt na pieniądz.'],

  [15, 'Hipoteza naturalnej stopy bezrobocia', 'Koncepcja, według której bezrobocie w długim okresie powraca do poziomu naturalnego niezależnie od inflacji.'],
  [15, 'Histereza', 'Opóźniony wpływ minionych zdarzeń gospodarczych na zdarzenia przyszłe.'],
  [15, 'Krzywa Phillipsa', 'Krzywa obrazująca krótkookresową odwrotną zależność między inflacją a bezrobociem.'],
  [15, 'Stopa bezrobocia stabilizująca inflację', 'Długookresowa stopa bezrobocia odpowiadająca stałej stopie inflacji.'],
  [15, 'Teoria adaptacyjnych oczekiwań', 'Koncepcja tworzenia oczekiwań inflacyjnych na podstawie historycznych wskaźników inflacji.'],
  [15, 'Teoria racjonalnych oczekiwań', 'Koncepcja optymalnego wykorzystywania wszystkich dostępnych informacji przy formułowaniu przewidywań.'],
  [15, 'Współczynnik poświęcenia', 'Procentowy spadek produkcji związany z obniżeniem inflacji o jeden punkt procentowy.'],

  [16, 'Interwencyjne instrumenty polityki podażowej', 'Instrumenty poprawiające funkcjonowanie rynków przez inwestycje w infrastrukturę, edukację i badania.'],
  [16, 'Krzywa Laffera', 'Krzywa obrazująca zależność między stawkami podatkowymi a dochodami podatkowymi.'],
  [16, 'Prywatyzacja', 'Przekazanie składników majątku publicznego w prywatne ręce.'],
  [16, 'Rynkowe instrumenty polityki podażowej', 'Instrumenty wzmacniające mechanizmy rynkowe i efektywność alokacji zasobów.'],

  [17, 'Europejski Bank Centralny (EBC)', 'Wspólny bank centralny krajów tworzących Unię Gospodarczą i Walutową.'],
  [17, 'Eurosystem', 'Struktura złożona z EBC i banków centralnych państw tworzących Unię Gospodarczą i Walutową.'],
  [17, 'Federalizm fiskalny', 'Integracja polityki fiskalnej grupy państw oparta na wspólnym budżecie, podatkach i transferach.'],
  [17, 'Jednolity rynek', 'Koncepcja swobodnego przepływu siły roboczej, kapitału, towarów i usług na obszarze UE.'],
  [17, 'Optymalny obszar walutowy', 'Grupa krajów, dla których optymalne jest przyjęcie wspólnej waluty i utworzenie unii walutowej.'],
  [17, 'Strefa Schengen', 'Obszar państw, na którym zniesiono kontrole na granicach wewnętrznych.'],
  [17, 'Unia Europejska', 'Rodzina demokratycznych krajów europejskich współpracujących na rzecz pokoju i dobrobytu.'],
  [17, 'Unia Gospodarcza i Walutowa', 'Unia walutowa krajów europejskich, w której funkcję wspólnej waluty pełni euro.'],
  [17, 'Wspólny obszar walutowy', 'Obszar geograficzny, na którym funkcję środka płatniczego pełni jedna waluta.'],
  [17, 'Wstrząs asymetryczny', 'Zdarzenie wywierające odmienny wpływ na popyt lub podaż zagregowaną w poszczególnych krajach.'],

  [18, 'Dług publiczny', 'Łączne zobowiązania państwa z tytułu zaciągniętych pożyczek.'],
  [18, 'Deficyt cykliczny', 'Deficyt wynikający z zaburzeń dochodów i wydatków budżetowych na skutek wahań koniunktury.'],
  [18, 'Deficyt strukturalny', 'Deficyt występujący niezależnie od cyklicznych wahań koniunktury.'],
  [18, 'Nadwyżka kapitałowa', 'Dodatnia różnica między ceną nieruchomości a wartością kredytu udzielonego na jej zakup.'],
  [18, 'Polityka makroostrożnościowa', 'Polityka ograniczająca ryzyko całego sektora finansowego przez regulacje wzmacniające jego stabilność.'],
  [18, 'Rynek subprime', 'Segment klientów o wysokim ryzyku niewypłacalności, zwykle nieuznawanych za standardowych kredytobiorców.'],
  [18, 'Ryzyko kredytowe', 'Ryzyko pogorszenia sytuacji banku wskutek niewykonania zobowiązań przez kredytobiorców.'],
  [18, 'Ryzyko płynności', 'Ryzyko, że bank nie będzie w stanie zaspokoić zapotrzebowania na wypłatę środków.'],
  [18, 'Ryzyko systemowe', 'Ryzyko niewydolności całego sektora finansowego.'],
  [18, 'Sekurytyzacja', 'Proces przekształcania wierzytelności kredytodawcy w papiery wartościowe przeznaczone do sprzedaży.'],
  [18, 'Spread', 'Różnica między średnim oprocentowaniem aktywów banku a oprocentowaniem jego zobowiązań.'],
  [18, 'Wycena według wartości rynkowej', 'Zasada wykazywania aktywów instytucji finansowej według ich wartości godziwej.'],
  [18, 'Zawłaszczenie regulacji', 'Sytuacja, w której regulator znajduje się pod nadmiernym wpływem interesów branży, którą ma regulować.']
].map(([chapter, term, definition]) => ({ chapter, term, definition }));

const macroFullBookOutline = macroBookChapters.map(chapter => ({
  number: chapter.number,
  pages: chapter.pages,
  topics: chapter.sections
}));

const macroGuide = (number, overview, qa) => ({ number, overview, qa });

const macroChapterGuides = [
  macroGuide(1, 'Rozdział wyjaśnia, dlaczego dochód całkowity jest równy wydatkom, jak oblicza się PKB, z jakich składników się składa oraz czym różnią się wartości realne od nominalnych.', [
    ['Co jednocześnie mierzy PKB?', 'Dochód całkowity uzyskany w gospodarce oraz wydatki na wytworzone dobra i usługi.'],
    ['Jakie są cztery składniki PKB?', 'Konsumpcja, inwestycje, wydatki publiczne i eksport netto.'],
    ['Dlaczego odróżnia się PKB realny od nominalnego?', 'Aby oddzielić zmianę wielkości produkcji od zmiany cen.']
  ]),
  macroGuide(2, 'Rozdział przedstawia sposób obliczania CPI, trudności związane z pomiarem kosztów utrzymania oraz metody porównywania wartości pieniężnych i stóp procentowych z różnych okresów.', [
    ['Co mierzy CPI?', 'Koszt reprezentatywnego koszyka dóbr i usług kupowanych przez konsumenta.'],
    ['Czym CPI różni się od deflatora PKB?', 'CPI dotyczy koszyka konsumenta, a deflator bieżącej produkcji krajowej.'],
    ['Jak otrzymać realną stopę procentową?', 'Należy skorygować stopę nominalną o inflację.']
  ]),
  macroGuide(3, 'Rozdział łączy poziom życia z produkcyjnością i pokazuje rolę kapitału, wiedzy technologicznej, zasobów naturalnych, edukacji, zdrowia, instytucji oraz polityki państwa we wzroście.', [
    ['Od czego zależy długookresowy poziom życia?', 'Przede wszystkim od produkcyjności gospodarki.'],
    ['Na czym polega efekt doganiania?', 'Uboższe kraje mogą rosnąć szybciej dzięki wysokim przyrostom kapitału i przejmowaniu technologii.'],
    ['Dlaczego instytucje są ważne dla wzrostu?', 'Prawa własności i stabilność sprzyjają inwestycjom oraz efektywnemu wykorzystaniu zasobów.']
  ]),
  macroGuide(4, 'Rozdział porządkuje pomiar rynku pracy i wyjaśnia bezrobocie naturalne, frykcyjne oraz strukturalne, a także wpływ poszukiwania pracy, płacy minimalnej, związków i płac efektywnościowych.', [
    ['Kto należy do zasobu siły roboczej?', 'Osoby pracujące oraz osoby bezrobotne aktywnie poszukujące pracy.'],
    ['Dlaczego bezrobocie frykcyjne jest nieuniknione?', 'Dopasowanie pracowników do odpowiednich miejsc pracy wymaga czasu.'],
    ['Jak płaca wyższa od równowagi może wpływać na bezrobocie?', 'Zwiększa podaż pracy i może ograniczać popyt przedsiębiorstw na pracowników.']
  ]),
  macroGuide(5, 'Rozdział opisuje instytucje systemu finansowego, tożsamości oszczędności i inwestycji oraz rynek funduszy pożyczkowych, na którym stopa procentowa równoważy podaż środków i popyt na nie.', [
    ['Jaka jest rola systemu finansowego?', 'Przenosi środki od oszczędzających do podmiotów finansujących inwestycje.'],
    ['Co tworzy podaż na rynku funduszy pożyczkowych?', 'Oszczędności narodowe.'],
    ['Jak deficyt budżetowy wpływa na oszczędności?', 'Zmniejsza oszczędności publiczne i narodowe.']
  ]),
  macroGuide(6, 'Rozdział wprowadza wartość pieniądza w czasie, procent składany, awersję do ryzyka, dywersyfikację, relację ryzyka i zwrotu oraz dwie metody myślenia o wycenie aktywów.', [
    ['Dlaczego wartość bieżąca jest mniejsza od przyszłej?', 'Dzisiejsze pieniądze można zainwestować i powiększyć o odsetki.'],
    ['Co usuwa dywersyfikacja?', 'Ogranicza ryzyko indywidualne, ale nie usuwa ryzyka zagregowanego.'],
    ['Co głosi hipoteza efektywności rynku?', 'Ceny aktywów odzwierciedlają dostępne informacje o ich wartości.']
  ]),
  macroGuide(7, 'Rozdział omawia funkcje i rodzaje pieniądza, działalność banków centralnych, kreację pieniądza w systemie rezerwy cząstkowej oraz narzędzia kontrolowania podaży pieniądza.', [
    ['Jakie funkcje pełni pieniądz?', 'Jest środkiem wymiany, jednostką rozliczeniową i środkiem przechowywania wartości.'],
    ['Jak banki kreują pieniądz?', 'Udzielając kredytów opartych na części utrzymywanych rezerw.'],
    ['Jak bank centralny wpływa na podaż pieniądza?', 'Wykorzystuje operacje rynkowe, stopy i inne narzędzia oddziałujące na płynność banków.']
  ]),
  macroGuide(8, 'Rozdział przedstawia ilościową teorię pieniądza, neutralność pieniądza, równanie ilościowe, efekt Fishera oraz społeczne i gospodarcze koszty inflacji i deflacji.', [
    ['Co łączy równanie ilościowe?', 'Ilość pieniądza i szybkość obiegu z poziomem cen i realną produkcją.'],
    ['Na czym polega neutralność pieniądza?', 'W długim okresie zmiana podaży pieniądza wpływa na zmienne nominalne, a nie realne.'],
    ['Co opisuje efekt Fishera?', 'Dostosowanie nominalnej stopy procentowej do zmian inflacji.']
  ]),
  macroGuide(9, 'Rozdział porządkuje przepływy dóbr i kapitału między krajami, pokazuje związek eksportu netto z odpływami kapitałowymi oraz wyjaśnia nominalny i realny kurs walutowy i parytet siły nabywczej.', [
    ['Co oznacza eksport netto?', 'Wartość eksportu pomniejszoną o wartość importu.'],
    ['Jak eksport netto łączy się z kapitałem?', 'Jest równy odpływom kapitałowym netto w ujęciu rachunkowym.'],
    ['Co mierzy realny kurs walutowy?', 'Relację wymiany dóbr krajowych na dobra zagraniczne.']
  ]),
  macroGuide(10, 'Rozdział łączy rynek funduszy pożyczkowych z rynkiem walutowym i analizuje wpływ deficytu budżetowego, polityki handlowej oraz ucieczki kapitału na gospodarkę otwartą.', [
    ['Co łączy dwa rynki modelu gospodarki otwartej?', 'Odpływy kapitałowe netto.'],
    ['Czy ograniczenie importu musi poprawić eksport netto?', 'Nie, ponieważ zmienia także kurs walutowy i przepływy kapitału.'],
    ['Czym jest ucieczka kapitału?', 'Nagłym spadkiem popytu na aktywa danego kraju.']
  ]),
  macroGuide(11, 'Rozdział definiuje trend i cykl koniunkturalny, klasyfikuje zmienne i wskaźniki oraz zestawia popytowe i podażowe, klasyczne i keynesowskie wyjaśnienia wahań gospodarki.', [
    ['Czym cykl różni się od trendu?', 'Cykl to wahania wokół długookresowego kierunku zmian.'],
    ['Po co stosuje się wskaźniki wyprzedzające?', 'Aby próbować przewidzieć przyszłe zmiany koniunktury.'],
    ['Co oznacza zmienna procykliczna?', 'Jej wartość jest dodatnio skorelowana z PKB.']
  ]),
  macroGuide(12, 'Rozdział buduje krzyż keynesowski i model IS–LM, wyjaśnia wydatki planowane, efekt mnożnikowy oraz wpływ polityki fiskalnej i pieniężnej na produkcję i stopę procentową.', [
    ['Kiedy gospodarka jest w równowadze w krzyżu keynesowskim?', 'Gdy wydatki planowane są równe produkcji rzeczywistej.'],
    ['Co opisuje krzywa IS?', 'Równowagę na rynku dóbr przy różnych kombinacjach produkcji i stopy procentowej.'],
    ['Co opisuje krzywa LM?', 'Równowagę na rynku pieniądza przy różnych kombinacjach produkcji i stopy procentowej.']
  ]),
  macroGuide(13, 'Rozdział przedstawia model zagregowanego popytu i podaży, wyjaśnia kształt i przesunięcia obu krzywych oraz analizuje skutki wstrząsów popytowych i podażowych.', [
    ['Dlaczego krzywa zagregowanego popytu opada?', 'Zmiana poziomu cen wpływa na realny majątek, stopy procentowe i eksport netto.'],
    ['Dlaczego długookresowa podaż jest pionowa?', 'Produkcję długookresową wyznaczają realne zasoby i technologia, a nie poziom cen.'],
    ['Co powoduje negatywny wstrząs podażowy?', 'Spadek produkcji i wzrost poziomu cen.']
  ]),
  macroGuide(14, 'Rozdział pokazuje wpływ podaży pieniądza, stóp procentowych, wydatków publicznych i podatków na zagregowany popyt oraz zestawia mnożnik z efektem wypierania i automatycznymi stabilizatorami.', [
    ['Jak polityka pieniężna wpływa na popyt?', 'Zmienia warunki na rynku pieniądza, stopy procentowe i wydatki.'],
    ['Na czym polega efekt wypierania?', 'Ekspansja fiskalna podnosi stopy i ogranicza część inwestycji prywatnych.'],
    ['Jak działają automatyczne stabilizatory?', 'Łagodzą zmianę popytu bez każdorazowej nowej decyzji władz.']
  ]),
  macroGuide(15, 'Rozdział wyjaśnia krótkookresową i długookresową krzywą Phillipsa, rolę oczekiwań i wstrząsów podażowych oraz koszty dezinflacji i znaczenie wiarygodnej polityki pieniężnej.', [
    ['Dlaczego krzywa Phillipsa przesuwa się?', 'Wpływają na nią oczekiwania inflacyjne i wstrząsy podażowe.'],
    ['Czy wyższa inflacja trwale obniża bezrobocie?', 'Nie, w długim okresie bezrobocie wraca do poziomu naturalnego.'],
    ['Co mierzy współczynnik poświęcenia?', 'Utratę produkcji związaną z obniżeniem inflacji.']
  ]),
  macroGuide(16, 'Rozdział rozróżnia rynkowe i interwencyjne instrumenty polityki podażowej oraz ocenia ich wpływ na zdolności produkcyjne, bodźce, kwalifikacje i funkcjonowanie rynków.', [
    ['Jaki jest cel polityki podażowej?', 'Zwiększenie możliwości produkcyjnych i poprawa funkcjonowania strony podażowej gospodarki.'],
    ['Czym są instrumenty rynkowe?', 'Działaniami wzmacniającymi bodźce cenowe i konkurencję.'],
    ['Czym są instrumenty interwencyjne?', 'Bezpośrednimi inwestycjami i działaniami państwa w infrastrukturze, edukacji i badaniach.']
  ]),
  macroGuide(17, 'Rozdział analizuje wspólną walutę, warunki optymalnego obszaru walutowego, mobilność pracy i kapitału, symetrię wstrząsów oraz rolę polityki fiskalnej w unii walutowej.', [
    ['Kiedy wspólna waluta jest mniej kosztowna?', 'Gdy gospodarki mają elastyczne płace, mobilne czynniki produkcji i podobne wstrząsy.'],
    ['Co daje federalizm fiskalny?', 'Pozwala łagodzić lokalne wstrząsy transferami w ramach wspólnego budżetu.'],
    ['Czym jest wstrząs asymetryczny?', 'Zdarzeniem wpływającym odmiennie na poszczególne kraje unii.']
  ]),
  macroGuide(18, 'Rozdział śledzi powstanie bańki mieszkaniowej, rozwój rynku subprime i sekurytyzacji, globalny kryzys finansowy oraz późniejszy kryzys długu publicznego i spór o konsolidację fiskalną.', [
    ['Jak sekurytyzacja zmienia kredyty?', 'Łączy wierzytelności i przekształca je w papiery wartościowe przeznaczone do sprzedaży.'],
    ['Czym ryzyko systemowe różni się od indywidualnego?', 'Dotyczy niewydolności całego systemu, a nie pojedynczej instytucji.'],
    ['Czym deficyt strukturalny różni się od cyklicznego?', 'Strukturalny istnieje niezależnie od cyklu, a cykliczny wynika z bieżących wahań koniunktury.']
  ])
];

const macroFormulaCatalog = [
  { chapter: 1, group: 'Rachunki narodowe', name: 'PKB metodą wydatkową', formula: 'Y = C + I + G + NX', variables: 'Y – PKB; C – konsumpcja; I – inwestycje; G – wydatki publiczne; NX – eksport netto', use: 'Rozdziela PKB na cztery kategorie wydatków.' },
  { chapter: 1, group: 'Handel', name: 'Eksport netto', formula: 'NX = X − M', variables: 'X – eksport; M – import', use: 'Oblicza saldo handlu dobrami i usługami.' },
  { chapter: 1, group: 'Ceny', name: 'Deflator PKB', formula: 'Deflator PKB = (PKB nominalny / PKB realny) × 100', variables: 'Rok bazowy ma wartość 100.', use: 'Mierzy poziom cen produkcji ujętej w PKB.' },
  { chapter: 2, group: 'Ceny', name: 'Wskaźnik CPI', formula: 'CPI = (koszt koszyka bieżący / koszt koszyka bazowy) × 100', variables: 'Koszyk bazowy pozostaje punktem odniesienia.', use: 'Mierzy zmianę kosztów utrzymania.' },
  { chapter: 2, group: 'Ceny', name: 'Stopa inflacji', formula: 'π = [(CPIₜ − CPIₜ₋₁) / CPIₜ₋₁] × 100%', variables: 'π – stopa inflacji.', use: 'Oblicza procentową zmianę wskaźnika cen.' },
  { chapter: 2, group: 'Stopy procentowe', name: 'Realna stopa procentowa', formula: 'r = i − π', variables: 'r – stopa realna; i – nominalna; π – inflacja', use: 'Koryguje nominalne oprocentowanie o inflację.' },
  { chapter: 3, group: 'Wzrost', name: 'Produkcyjność pracy', formula: 'produkcyjność = Y / L', variables: 'Y – produkcja; L – nakład pracy', use: 'Mierzy produkcję przypadającą na jednostkę pracy.' },
  { chapter: 3, group: 'Wzrost', name: 'Funkcja produkcji', formula: 'Y = A·F(K, L)', variables: 'A – technologia; K – kapitał; L – praca', use: 'Łączy produkcję z zasobami i technologią.' },
  { chapter: 4, group: 'Rynek pracy', name: 'Stopa bezrobocia', formula: 'u = U / (E + U) × 100%', variables: 'U – bezrobotni; E – pracujący', use: 'Mierzy udział bezrobotnych w zasobie siły roboczej.' },
  { chapter: 4, group: 'Rynek pracy', name: 'Wskaźnik aktywności zawodowej', formula: 'LFPR = (E + U) / P × 100%', variables: 'P – populacja dorosłych', use: 'Mierzy udział aktywnych zawodowo w populacji.' },
  { chapter: 5, group: 'Oszczędności', name: 'Oszczędności narodowe', formula: 'S = Y − C − G', variables: 'Y – dochód; C – konsumpcja; G – wydatki publiczne', use: 'Pokazuje część dochodu niewydaną na konsumpcję prywatną i publiczną.' },
  { chapter: 5, group: 'Oszczędności', name: 'Oszczędności prywatne i publiczne', formula: 'S = (Y − T − C) + (T − G)', variables: 'T – podatki netto', use: 'Rozdziela oszczędności narodowe na sektor prywatny i publiczny.' },
  { chapter: 6, group: 'Wartość pieniądza w czasie', name: 'Wartość przyszła', formula: 'FV = PV(1 + r)ⁿ', variables: 'PV – wartość bieżąca; r – stopa; n – liczba okresów', use: 'Oblicza wartość inwestycji po kapitalizacji.' },
  { chapter: 6, group: 'Wartość pieniądza w czasie', name: 'Wartość bieżąca', formula: 'PV = FV / (1 + r)ⁿ', variables: 'FV – wartość przyszła', use: 'Dyskontuje przyszłą płatność do wartości dzisiejszej.' },
  { chapter: 7, group: 'Bankowość', name: 'Prosty mnożnik pieniężny', formula: 'm = 1 / rr', variables: 'rr – stopa rezerw', use: 'Pokazuje maksymalną kreację depozytów w uproszczonym modelu.' },
  { chapter: 8, group: 'Pieniądz', name: 'Równanie ilościowe', formula: 'M × V = P × Y', variables: 'M – pieniądz; V – szybkość obiegu; P – ceny; Y – realna produkcja', use: 'Łączy podaż pieniądza z nominalną wartością produkcji.' },
  { chapter: 8, group: 'Stopy procentowe', name: 'Efekt Fishera', formula: 'i = r + πᵉ', variables: 'i – stopa nominalna; r – realna; πᵉ – oczekiwana inflacja', use: 'Pokazuje wpływ oczekiwanej inflacji na stopę nominalną.' },
  { chapter: 9, group: 'Gospodarka otwarta', name: 'Oszczędności w gospodarce otwartej', formula: 'S = I + NCO', variables: 'I – inwestycje krajowe; NCO – odpływy kapitałowe netto', use: 'Pokazuje dwa zastosowania oszczędności narodowych.' },
  { chapter: 9, group: 'Gospodarka otwarta', name: 'Tożsamość przepływów', formula: 'NCO = NX', variables: 'NCO – odpływy kapitałowe netto; NX – eksport netto', use: 'Łączy przepływ kapitału z przepływem dóbr.' },
  { chapter: 9, group: 'Kursy walutowe', name: 'Realny kurs walutowy', formula: 'ε = e × P / P*', variables: 'e – kurs nominalny; P – ceny krajowe; P* – ceny zagraniczne', use: 'Porównuje ceny dóbr krajowych i zagranicznych.' },
  { chapter: 12, group: 'Mnożnik', name: 'Mnożnik wydatkowy', formula: 'k = 1 / (1 − MPC)', variables: 'MPC – krańcowa skłonność do konsumpcji', use: 'Oblicza zmianę dochodu po zmianie wydatków autonomicznych w prostym modelu.' },
  { chapter: 12, group: 'Oszczędności', name: 'Krańcowe skłonności', formula: 'MPC + MPS = 1', variables: 'MPS – krańcowa skłonność do oszczędzania', use: 'Dzieli dodatkowy dochód między konsumpcję i oszczędności.' },
  { chapter: 13, group: 'Koniunktura', name: 'Luka produktowa', formula: 'luka = (Y − Y*) / Y* × 100%', variables: 'Y – produkcja faktyczna; Y* – naturalny poziom produkcji', use: 'Mierzy odchylenie produkcji od poziomu naturalnego.' },
  { chapter: 15, group: 'Inflacja i bezrobocie', name: 'Krzywa Phillipsa z oczekiwaniami', formula: 'π = πᵉ − β(u − u*) + v', variables: 'π – inflacja; u – bezrobocie; u* – stopa naturalna; v – wstrząs podażowy', use: 'Porządkuje krótkookresowe źródła inflacji.' },
  { chapter: 15, group: 'Dezinflacja', name: 'Współczynnik poświęcenia', formula: 'SR = utrata produkcji / spadek inflacji', variables: 'Wielkości muszą obejmować ten sam okres.', use: 'Mierzy koszt obniżenia inflacji.' },
  { chapter: 18, group: 'Finanse publiczne', name: 'Relacja długu do PKB', formula: 'd = D / Y × 100%', variables: 'D – dług publiczny; Y – nominalny PKB', use: 'Porównuje dług publiczny z rozmiarem gospodarki.' }
];
